import Foundation

extension FreeMovie {
    // MARK: Chunk 4
    static let _smc04: [FreeMovie] = [
        FreeMovie(
            id: "ia-the-big-combo-1955",
            title: "The Big Combo",
            posterURL: "https://image.tmdb.org/t/p/w500/6XVBCFP7LVHnVPQFqLPJHPFLqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6XVBCFP7LVHnVPQFqLPJHPFLqHE.jpg",
            overview: "A police detective becomes obsessed with bringing down a crime boss. Stunning cinematography and brutal noir!",
            releaseDate: "1955-02-13",
            runtime: 87,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheBigCombo1955/The%20Big%20Combo%20%281955%29.mp4",
            trailerURL: nil,
            cast: ["Cornel Wilde", "Richard Conte", "Jean Wallace"],
            director: "Joseph H. Lewis",
            year: 1955,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-too-late-for-tears-1949",
            title: "Too Late for Tears",
            posterURL: "https://image.tmdb.org/t/p/w500/9QLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9QLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "A couple finds a bag of money thrown into their car, but the wife's greed leads to murder. Lizabeth Scott at her most dangerous!",
            releaseDate: "1949-08-13",
            runtime: 99,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 7.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TooLateForTears1949/Too%20Late%20for%20Tears%20%281949%29.mp4",
            trailerURL: nil,
            cast: ["Lizabeth Scott", "Don DeFore", "Dan Duryea"],
            director: "Byron Haskin",
            year: 1949,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-narrow-margin-1952",
            title: "The Narrow Margin",
            posterURL: "https://image.tmdb.org/t/p/w500/cXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/cXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "A detective must protect a mob widow on a cross-country train trip while assassins close in. Tense, claustrophobic noir!",
            releaseDate: "1952-05-04",
            runtime: 71,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 7.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheNarrowMargin1952/The%20Narrow%20Margin%20%281952%29.mp4",
            trailerURL: nil,
            cast: ["Charles McGraw", "Marie Windsor", "Jacqueline White"],
            director: "Richard Fleischer",
            year: 1952,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎪 MUSICALS & SPECTACLES - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-royal-wedding-1951",
            title: "Royal Wedding",
            posterURL: "https://image.tmdb.org/t/p/w500/pXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/pXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "A brother-sister dance team finds love in London during the royal wedding. Features Fred Astaire dancing on the ceiling!",
            releaseDate: "1951-03-23",
            runtime: 93,
            genre: [.musical, .comedy, .romance],
            rating: "G",
            imdbRating: 6.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/RoyalWedding1951/Royal%20Wedding%20%281951%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=CsoYyDlYU8M",
            cast: ["Fred Astaire", "Jane Powell", "Peter Lawford"],
            director: "Stanley Donen",
            year: 1951,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-swing-time-1936",
            title: "Swing Time",
            posterURL: "https://image.tmdb.org/t/p/w500/sXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/sXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "A dancer bets he can earn $25,000 to win back his fiancée, but falls for his dance instructor instead. Fred & Ginger at their best!",
            releaseDate: "1936-08-27",
            runtime: 103,
            genre: [.musical, .comedy, .romance],
            rating: "G",
            imdbRating: 7.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/SwingTime1936/Swing%20Time%20%281936%29.mp4",
            trailerURL: nil,
            cast: ["Fred Astaire", "Ginger Rogers", "Victor Moore"],
            director: "George Stevens",
            year: 1936,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🔬 SCI-FI GEMS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-things-to-come-1936",
            title: "Things to Come",
            posterURL: "https://image.tmdb.org/t/p/w500/tXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/tXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "H.G. Wells' vision of the future from 1936 to 2036. Groundbreaking sci-fi epic with stunning production design!",
            releaseDate: "1936-02-21",
            runtime: 100,
            genre: [.scifi, .drama, .war],
            rating: "G",
            imdbRating: 6.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThingsToCome1936/Things%20to%20Come%20%281936%29.mp4",
            trailerURL: nil,
            cast: ["Raymond Massey", "Edward Chapman", "Ralph Richardson"],
            director: "William Cameron Menzies",
            year: 1936,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-day-the-earth-stood-still-trailer",
            title: "The Day the Earth Stood Still (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/fXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/fXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "An alien visitor and his robot companion deliver an ultimatum to Earth. Classic sci-fi that influenced generations!",
            releaseDate: "1951-09-28",
            runtime: 3,
            genre: [.scifi, .drama],
            rating: "G",
            imdbRating: 7.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheDayTheEarthStoodStill1951Trailer/The%20Day%20the%20Earth%20Stood%20Still%20%281951%29%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=0hEKRc9KGVE",
            cast: ["Michael Rennie", "Patricia Neal", "Hugh Marlowe"],
            director: "Robert Wise",
            year: 1951,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-robot-monster-1953",
            title: "Robot Monster",
            posterURL: "https://image.tmdb.org/t/p/w500/rXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/rXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "An alien in a gorilla suit with a diving helmet destroys humanity. Legendarily bad sci-fi that's incredibly entertaining!",
            releaseDate: "1953-06-24",
            runtime: 66,
            genre: [.scifi, .horror],
            rating: "G",
            imdbRating: 2.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/RobotMonster1953/Robot%20Monster%20%281953%29.mp4",
            trailerURL: nil,
            cast: ["George Nader", "Claudia Barrett", "Selena Royle"],
            director: "Phil Tucker",
            year: 1953,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-cat-women-of-the-moon-1953",
            title: "Cat-Women of the Moon",
            posterURL: "https://image.tmdb.org/t/p/w500/wXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/wXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "Astronauts land on the moon and discover a civilization of telepathic women. Campy 50s sci-fi at its finest!",
            releaseDate: "1953-09-03",
            runtime: 64,
            genre: [.scifi, .adventure],
            rating: "G",
            imdbRating: 3.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CatWomenOfTheMoon1953/Cat-Women%20of%20the%20Moon%20%281953%29.mp4",
            trailerURL: nil,
            cast: ["Sonny Tufts", "Victor Jory", "Marie Windsor"],
            director: "Arthur Hilton",
            year: 1953,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-teenagers-from-outer-space-1959",
            title: "Teenagers from Outer Space",
            posterURL: "https://image.tmdb.org/t/p/w500/xXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/xXLPJHPJLqHFLCJHvLPKLqHEqHE.jpg",
            overview: "Alien teenagers come to Earth to raise giant lobsters for food. A cult classic of 50s sci-fi!",
            releaseDate: "1959-06-01",
            runtime: 86,
            genre: [.scifi, .horror],
            rating: "G",
            imdbRating: 4.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TeenagersFromOuterSpace1959/Teenagers%20from%20Outer%20Space%20%281959%29.mp4",
            trailerURL: nil,
            cast: ["David Love", "Dawn Bender", "Harvey B. Dunn"],
            director: "Tom Graeff",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // ⚔️ WAR FILMS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-african-queen-trailer",
            title: "The African Queen (Restored Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/lLHmqn7WUYoGbIFd8i5J0IX7QWj.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/lLHmqn7WUYoGbIFd8i5J0IX7QWj.jpg",
            overview: "A gin-swilling riverboat captain and a prim missionary navigate dangerous waters in WWI Africa. Bogart & Hepburn magic!",
            releaseDate: "1951-12-26",
            runtime: 4,
            genre: [.adventure, .war, .romance],
            rating: "PG",
            imdbRating: 7.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheAfricanQueenTrailer/The%20African%20Queen%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=POIU874Bxhg",
            cast: ["Humphrey Bogart", "Katharine Hepburn"],
            director: "John Huston",
            year: 1951,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-all-quiet-western-front-1930",
            title: "All Quiet on the Western Front",
            posterURL: "https://image.tmdb.org/t/p/w500/qm5MKJKRT1rkMEVmhFGFHLLsRGM.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qm5MKJKRT1rkMEVmhFGFHLLsRGM.jpg",
            overview: "Young German soldiers face the horrors of WWI. The original anti-war masterpiece that won Best Picture!",
            releaseDate: "1930-04-21",
            runtime: 152,
            genre: [.war, .drama],
            rating: "PG",
            imdbRating: 8.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AllQuietOnTheWesternFront1930/All%20Quiet%20on%20the%20Western%20Front%20%281930%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=yrEJFnOV4ek",
            cast: ["Lew Ayres", "Louis Wolheim", "John Wray"],
            director: "Lewis Milestone",
            year: 1930,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-sahara-1943",
            title: "Sahara",
            posterURL: "https://image.tmdb.org/t/p/w500/3wBh2kRE1sDxj2gTcXeD1EiY8jf.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3wBh2kRE1sDxj2gTcXeD1EiY8jf.jpg",
            overview: "An American tank crew fights for survival in the North African desert during WWII. Humphrey Bogart in action!",
            releaseDate: "1943-11-11",
            runtime: 97,
            genre: [.war, .action, .drama],
            rating: "PG",
            imdbRating: 7.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Sahara1943/Sahara%20%281943%29.mp4",
            trailerURL: nil,
            cast: ["Humphrey Bogart", "Bruce Bennett", "J. Carrol Naish"],
            director: "Zoltán Korda",
            year: 1943,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-a-walk-in-the-sun-1945",
            title: "A Walk in the Sun",
            posterURL: "https://image.tmdb.org/t/p/w500/1JmVPJnvnL0GZxN4BrWxNhXLqVF.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/1JmVPJnvnL0GZxN4BrWxNhXLqVF.jpg",
            overview: "American soldiers fight their way through Italy during WWII. Raw, realistic war drama!",
            releaseDate: "1945-12-25",
            runtime: 117,
            genre: [.war, .drama],
            rating: "PG",
            imdbRating: 7.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AWalkInTheSun1945/A%20Walk%20in%20the%20Sun%20%281945%29.mp4",
            trailerURL: nil,
            cast: ["Dana Andrews", "Richard Conte", "John Ireland"],
            director: "Lewis Milestone",
            year: 1945,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-steel-helmet-1951",
            title: "The Steel Helmet",
            posterURL: "https://image.tmdb.org/t/p/w500/bvgL3nLSFMgXD7WXxWxQPKLnSfr.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bvgL3nLSFMgXD7WXxWxQPKLnSfr.jpg",
            overview: "A tough Army sergeant leads a ragtag squad during the Korean War. Sam Fuller's gritty, unflinching war classic!",
            releaseDate: "1951-01-02",
            runtime: 85,
            genre: [.war, .drama],
            rating: "PG",
            imdbRating: 7.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheSteelHelmet1951/The%20Steel%20Helmet%20%281951%29.mp4",
            trailerURL: nil,
            cast: ["Gene Evans", "Robert Hutton", "Steve Brodie"],
            director: "Samuel Fuller",
            year: 1951,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-gung-ho-1943",
            title: "Gung Ho!",
            posterURL: "https://image.tmdb.org/t/p/w500/sP7KEQqahXBTNhL9cfV0qKH4B7w.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/sP7KEQqahXBTNhL9cfV0qKH4B7w.jpg",
            overview: "The true story of Carlson's Raiders and their daring WWII assault on Makin Island. Intense combat action!",
            releaseDate: "1943-12-20",
            runtime: 88,
            genre: [.war, .action],
            rating: "PG",
            imdbRating: 6.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/GungHo1943/Gung%20Ho%21%20%281943%29.mp4",
            trailerURL: nil,
            cast: ["Randolph Scott", "Grace McDonald", "Alan Curtis"],
            director: "Ray Enright",
            year: 1943,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎭 MORE DRAMA - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-grapes-of-wrath-trailer",
            title: "The Grapes of Wrath (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/4rsb5AuC2hfREpoS1205z9KVJPQ.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/4rsb5AuC2hfREpoS1205z9KVJPQ.jpg",
            overview: "A Dust Bowl family travels to California seeking a better life. Henry Fonda in John Ford's masterpiece!",
            releaseDate: "1940-01-24",
            runtime: 3,
            genre: [.drama],
            rating: "G",
            imdbRating: 8.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGrapesOfWrath1940Trailer/The%20Grapes%20of%20Wrath%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=jA7iHVLuGV8",
            cast: ["Henry Fonda", "Jane Darwell", "John Carradine"],
            director: "John Ford",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-phantom-carriage-1921",
            title: "The Phantom Carriage",
            posterURL: "https://image.tmdb.org/t/p/w500/sSJFMYE3n11JfZXYDYEGpq8nBvC.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/sSJFMYE3n11JfZXYDYEGpq8nBvC.jpg",
            overview: "On New Year's Eve, a drunkard recounts his wasted life as Death's carriage approaches. Inspired Ingmar Bergman!",
            releaseDate: "1921-01-01",
            runtime: 107,
            genre: [.drama, .fantasy, .horror],
            rating: "PG",
            imdbRating: 8.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePhantomCarriage1921/The%20Phantom%20Carriage%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Victor Sjöström", "Hilda Borgström"],
            director: "Victor Sjöström",
            year: 1921,
            language: "Silent",
            country: "SE",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-count-of-monte-cristo-1934",
            title: "The Count of Monte Cristo",
            posterURL: "https://image.tmdb.org/t/p/w500/d5J2lsQnSzZdVCnCLK1ZXJF2Pqr.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/d5J2lsQnSzZdVCnCLK1ZXJF2Pqr.jpg",
            overview: "A wrongly imprisoned man escapes and uses a hidden treasure to exact revenge on those who betrayed him. The ultimate revenge saga!",
            releaseDate: "1934-09-01",
            runtime: 113,
            genre: [.adventure, .drama, .romance],
            rating: "G",
            imdbRating: 7.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheCountOfMonteCristo1934/The%20Count%20of%20Monte%20Cristo%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["Robert Donat", "Elissa Landi", "Louis Calhern"],
            director: "Rowland V. Lee",
            year: 1934,
            language: "English",
            country: "US",
            isAvailable: true
        )
    ]

    // MARK: - Chunk 3
    static let _sampleMovies_chunk3: [FreeMovie] = [
        FreeMovie(
            id: "ia-the-lost-weekend-trailer",
            title: "The Lost Weekend (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/7cMPxiGJBM5dRJPGGfNVuJ3IDTQ.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/7cMPxiGJBM5dRJPGGfNVuJ3IDTQ.jpg",
            overview: "An alcoholic writer struggles through a devastating four-day bender. Ray Milland won Best Actor for this searing drama!",
            releaseDate: "1945-11-16",
            runtime: 4,
            genre: [.drama],
            rating: "PG",
            imdbRating: 7.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLostWeekend1945Trailer/The%20Lost%20Weekend%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=PBSH0YDNM8s",
            cast: ["Ray Milland", "Jane Wyman", "Phillip Terry"],
            director: "Billy Wilder",
            year: 1945,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-mark-of-zorro-1920",
            title: "The Mark of Zorro",
            posterURL: "https://image.tmdb.org/t/p/w500/lMW0FX2g2KJzLRrHhLKCJbXPxGD.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/lMW0FX2g2KJzLRrHhLKCJbXPxGD.jpg",
            overview: "A nobleman leads a double life as a masked vigilante fighting tyranny in old California. The original swashbuckler!",
            releaseDate: "1920-11-05",
            runtime: 90,
            genre: [.adventure, .action, .romance],
            rating: "G",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheMarkOfZorro1920/The%20Mark%20of%20Zorro%20%281920%29.mp4",
            trailerURL: nil,
            cast: ["Douglas Fairbanks", "Marguerite De La Motte", "Noah Beery"],
            director: "Fred Niblo",
            year: 1920,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
    ]
}
