import Foundation

extension FreeMovie {
    // MARK: Chunk 2
    static let _smc02: [FreeMovie] = [
        FreeMovie(
            id: "ia-suddenly-1954",
            title: "Suddenly",
            posterURL: "https://image.tmdb.org/t/p/w500/4Q3Hnq5x6vT7c2Y2bYv6wGxqf8Q.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9T2oM5A3tP2v1n7aL3k5j8dS7Qw.jpg",
            overview: "Three assassins take over a family's home to kill the President. Frank Sinatra as a psychopath!",
            releaseDate: "1954-10-07",
            runtime: 77,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Suddenly_1954/Suddenly_1954_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=H2e1x5fH0t8",
            cast: ["Frank Sinatra", "Sterling Hayden"],
            director: "Lewis Allen",
            year: 1954,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-strange-love-of-martha-ivers-1946",
            title: "The Strange Love of Martha Ivers",
            posterURL: "https://image.tmdb.org/t/p/w500/9QhV2jV1oZb0HqM7mXkV8qY4VhL.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8m3l8sYx9fT6jQwV7k1f5h2p3nD.jpg",
            overview: "A childhood secret binds three people in a web of love, lies, and murder. Kirk Douglas' film debut!",
            releaseDate: "1946-10-16",
            runtime: 116,
            genre: [.drama, .crime, .thriller],
            rating: "PG",
            imdbRating: 7.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheStrangeLoveOfMarthaIvers/TheStrangeLoveOfMarthaIvers_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=G6k4dB1V0d4",
            cast: ["Barbara Stanwyck", "Van Heflin", "Kirk Douglas"],
            director: "Lewis Milestone",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🚀 SCI-FI & FANTASY
        // ============================================
        
        FreeMovie(
            id: "ia-metropolis-1927",
            title: "Metropolis",
            posterURL: "https://image.tmdb.org/t/p/w500/hUK9rewffKGqtXynH13BPqnsTm4.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bHI8f6VJHBjzJ7NWmQxMNiKL9Dv.jpg",
            overview: "In a futuristic city sharply divided between working class and city planners, a woman sparks revolution. A sci-fi masterpiece!",
            releaseDate: "1927-01-10",
            runtime: 153,
            genre: [.scifi, .drama],
            rating: "G",
            imdbRating: 8.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Metropolis_201610/Metropolis.mp4",
            trailerURL: "https://www.youtube.com/watch?v=Q0NzaJLQSRU",
            cast: ["Brigitte Helm", "Alfred Abel", "Gustav Fröhlich"],
            director: "Fritz Lang",
            year: 1927,
            language: "Silent",
            country: "DE",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-plan-9-from-outer-space-1959",
            title: "Plan 9 from Outer Space",
            posterURL: "https://image.tmdb.org/t/p/w500/9dVZ0KuQWmv2qkCw4qJ9Gx7Vw3K.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/1Gx0S4P0sRti3cfF5oSZX8FoLwq.jpg",
            overview: "Aliens raise the dead to stop humanity. Ed Wood's legendary 'worst film ever' is incredibly entertaining!",
            releaseDate: "1959-07-22",
            runtime: 79,
            genre: [.scifi, .horror],
            rating: "PG",
            imdbRating: 4.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Plan_9_from_Outer_Space_1959/Plan_9_from_Outer_Space_1959_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=u2ukRYsYPmo",
            cast: ["Bela Lugosi", "Tor Johnson", "Vampira"],
            director: "Ed Wood",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-voyage-to-prehistoric-planet-1965",
            title: "Voyage to the Prehistoric Planet",
            posterURL: "https://archive.org/services/img/VoyageToThePrehistoricPlanet1965",
            backdropURL: nil,
            overview: "Astronauts land on Venus and encounter dinosaurs and hostile aliens! Campy 60s sci-fi adventure.",
            releaseDate: "1965-01-01",
            runtime: 80,
            genre: [.scifi, .adventure],
            rating: "G",
            imdbRating: 4.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/VoyageToThePrehistoricPlanet1965/Voyage%20to%20the%20Prehistoric%20Planet%20%281965%29.mp4",
            trailerURL: nil,
            cast: ["Basil Rathbone", "Faith Domergue"],
            director: "Curtis Harrington",
            year: 1965,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-attack-of-50-foot-woman-1958",
            title: "Attack of the 50 Foot Woman",
            posterURL: "https://image.tmdb.org/t/p/w500/dvbkFKW3iVaWd8bWHDKCd5FHpXz.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/7s8PgVFQPPWQ8gvKREMNAQOMF9s.jpg",
            overview: "A woman grows to giant size after an alien encounter and seeks revenge on her cheating husband. Iconic B-movie!",
            releaseDate: "1958-05-19",
            runtime: 65,
            genre: [.scifi, .horror],
            rating: "PG",
            imdbRating: 4.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AttackOfThe50FootWoman/Attack%20of%20the%2050%20Foot%20Woman.mp4",
            trailerURL: "https://www.youtube.com/watch?v=vJRh2QzCsOw",
            cast: ["Allison Hayes", "William Hudson"],
            director: "Nathan Juran",
            year: 1958,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🤠 ACTION & ADVENTURE
        // ============================================
        
        FreeMovie(
            id: "ia-the-general-1926",
            title: "The General",
            posterURL: "https://image.tmdb.org/t/p/w500/mCU7HLyxAmLdkl4BRz2iJy8pInd.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/mM7p7JjJjZZ8Yr0cPSLXxGKJGN7.jpg",
            overview: "Buster Keaton's masterpiece! A train engineer pursues his stolen locomotive through enemy lines in the Civil War.",
            releaseDate: "1926-12-31",
            runtime: 75,
            genre: [.comedy, .action, .adventure],
            rating: "G",
            imdbRating: 8.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGeneral1926/The%20General%20%281926%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=iHlBLKUz9JA",
            cast: ["Buster Keaton", "Marion Mack"],
            director: "Buster Keaton",
            year: 1926,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-the-fast-and-the-furious-1955",
            title: "The Fast and the Furious",
            posterURL: "https://image.tmdb.org/t/p/w500/tqR4K9KQF8aF2F8p6oLJmX6cOGF.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/fuTZJ8yJb1mWgV8nUQJ4x6kQv3P.jpg",
            overview: "The ORIGINAL! A wrongly accused man kidnaps a woman and enters a cross-border car race to escape.",
            releaseDate: "1955-02-15",
            runtime: 73,
            genre: [.action, .thriller],
            rating: "PG",
            imdbRating: 5.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheFastAndTheFurious_1955/TheFastAndTheFurious_1955_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=hsQyDSmJ46c",
            cast: ["John Ireland", "Dorothy Malone"],
            director: "John Ireland",
            year: 1955,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-hercules-1958",
            title: "Hercules",
            posterURL: "https://image.tmdb.org/t/p/w500/6qJ1UqPwXhJPjKDMqL6L9M6tE8z.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/2vLkQ3BPvUW5f6u3Q0L6N2P5eHt.jpg",
            overview: "Steve Reeves stars as the legendary hero in this sword-and-sandal epic that launched a genre!",
            releaseDate: "1958-02-20",
            runtime: 107,
            genre: [.adventure, .action, .fantasy],
            rating: "G",
            imdbRating: 6.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Hercules1958/Hercules%20%281958%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=8X0FzZGhJdE",
            cast: ["Steve Reeves", "Sylva Koscina"],
            director: "Pietro Francisci",
            year: 1958,
            language: "English",
            country: "IT",
            isAvailable: true
        ),
        
        // ============================================
        // 🎨 ANIMATION (Blender Open Movies - HIGH QUALITY!)
        // ============================================
        
        FreeMovie(
            id: "blender-big-buck-bunny",
            title: "Big Buck Bunny",
            posterURL: "https://i.ytimg.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
            backdropURL: "https://ia801504.us.archive.org/11/items/BigBuckBunny_124/BigBuckBunny_124.thumbs/BigBuckBunny_124_000005.jpg",
            overview: "A lovable giant bunny takes on three bullying rodents. Stunning open-source animation in 4K!",
            releaseDate: "2008-04-10",
            runtime: 10,
            genre: [.animation, .comedy, .family],
            rating: "G",
            imdbRating: 6.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4",
            trailerURL: "https://www.youtube.com/watch?v=YE7VzlLtp-4",
            cast: [],
            director: "Sacha Goedegebure",
            year: 2008,
            language: "Silent",
            country: "NL",
            isAvailable: true
        ),
        FreeMovie(
            id: "blender-sintel",
            title: "Sintel",
            posterURL: "https://i.ytimg.com/vi/eRsGyueVLvQ/hqdefault.jpg",
            backdropURL: "https://ia601404.us.archive.org/2/items/Sintel/Sintel.thumbs/Sintel_000001.jpg",
            overview: "A young woman searches for her lost dragon companion. Emotionally powerful short film with stunning visuals!",
            releaseDate: "2010-09-27",
            runtime: 15,
            genre: [.animation, .fantasy, .adventure],
            rating: "G",
            imdbRating: 7.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Sintel/Sintel.mp4",
            trailerURL: "https://www.youtube.com/watch?v=eRsGyueVLvQ",
            cast: [],
            director: "Colin Levy",
            year: 2010,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        FreeMovie(
            id: "blender-tears-of-steel",
            title: "Tears of Steel",
            posterURL: "https://i.ytimg.com/vi/41hv2tW5Lc4/hqdefault.jpg",
            backdropURL: "https://ia801406.us.archive.org/33/items/TearOfSteel/TearOfSteel.thumbs/TearOfSteel_000001.jpg",
            overview: "In a dystopian future, scientists desperately work to save humanity. Groundbreaking VFX meets emotional storytelling!",
            releaseDate: "2012-09-26",
            runtime: 12,
            genre: [.scifi, .animation, .drama],
            rating: "PG",
            imdbRating: 6.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TearOfSteel/TearOfSteel.mp4",
            trailerURL: "https://www.youtube.com/watch?v=41hv2tW5Lc4",
            cast: ["Derek de Lint", "Sergio Hasselbaink"],
            director: "Ian Hubert",
            year: 2012,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        FreeMovie(
            id: "blender-elephants-dream",
            title: "Elephants Dream",
            posterURL: "https://i.ytimg.com/vi/TLkA0RELQ1g/hqdefault.jpg",
            backdropURL: "https://ia601508.us.archive.org/10/items/ElephantsDream/ElephantsDream.thumbs/ElephantsDream_000001.jpg",
            overview: "Two characters explore a surreal machine world. The first Blender open movie project!",
            releaseDate: "2006-05-18",
            runtime: 11,
            genre: [.animation, .scifi, .fantasy],
            rating: "G",
            imdbRating: 6.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=TLkA0RELQ1g",
            cast: ["Tygo Gernandt", "Cas Jansen"],
            director: "Bassam Kurdali",
            year: 2006,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        // ============================================
        // 📚 CULT CLASSICS & BONUS
        // ============================================
        
        FreeMovie(
            id: "ia-the-cabinet-of-dr-caligari-1920",
            title: "The Cabinet of Dr. Caligari",
            posterURL: "https://image.tmdb.org/t/p/w500/aqwETuhp7RkKhFgPihXAT5E9LFQ.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3qdAm3lBN2OJVtKRJOGHYvKY3pJ.jpg",
            overview: "A hypnotist uses a sleepwalker to commit murders. The iconic German Expressionist horror masterpiece!",
            releaseDate: "1920-02-26",
            runtime: 76,
            genre: [.horror, .fantasy, .mystery],
            rating: "PG",
            imdbRating: 8.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/thecabinetofdr.caligari/The%20Cabinet%20of%20Dr.%20Caligari%20%281920%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=IP0KB2XC29o",
            cast: ["Werner Krauss", "Conrad Veidt"],
            director: "Robert Wiene",
            year: 1920,
            language: "Silent",
            country: "DE",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-phantom-of-the-opera-1925",
            title: "The Phantom of the Opera",
            posterURL: "https://image.tmdb.org/t/p/w500/mNiZ0OhWkqL9lHw4lxQpHZ0LWLB.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/k9qIbDqvqtMYDLJQ6dUVJjzKOVL.jpg",
            overview: "A disfigured musical genius haunts the Paris Opera House. Lon Chaney's legendary makeup remains iconic!",
            releaseDate: "1925-09-06",
            runtime: 93,
            genre: [.horror, .drama, .romance],
            rating: "G",
            imdbRating: 7.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePhantomOfTheOpera1925/The%20Phantom%20of%20the%20Opera%20%281925%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=BXxGx3GXbag",
            cast: ["Lon Chaney", "Mary Philbin"],
            director: "Rupert Julian",
            year: 1925,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-santa-claus-conquers-martians-1964",
            title: "Santa Claus Conquers the Martians",
            posterURL: "https://image.tmdb.org/t/p/w500/jVJ1f7YD4hqfJkgLTIQMWTRt6J.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/wQTYuG8x0ALHnCyYFD5VyMPVq3v.jpg",
            overview: "Martians kidnap Santa to make toys for their children. So bad it's legendary! Perfect for ironic holiday viewing.",
            releaseDate: "1964-11-14",
            runtime: 81,
            genre: [.scifi, .comedy, .family],
            rating: "G",
            imdbRating: 2.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/SantaClausConquersTheMartians/Santa%20Claus%20Conquers%20the%20Martians.mp4",
            trailerURL: "https://www.youtube.com/watch?v=6uCYqKU5oNU",
            cast: ["John Call", "Leonard Hicks", "Pia Zadora"],
            director: "Nicholas Webster",
            year: 1964,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🔥 MORE ACTION CLASSICS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-scarlet-pimpernel-1934",
            title: "The Scarlet Pimpernel",
            posterURL: "https://image.tmdb.org/t/p/w500/vZqCh2iFjsGx2sJdBqVdJHKPCJE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/vZqCh2iFjsGx2sJdBqVdJHKPCJE.jpg",
            overview: "A dashing English nobleman leads a double life, rescuing French aristocrats from the guillotine during the Reign of Terror. The original superhero!",
            releaseDate: "1934-12-01",
            runtime: 97,
            genre: [.adventure, .romance, .drama],
            rating: "G",
            imdbRating: 7.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheScarletPimpernel1934/The%20Scarlet%20Pimpernel%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["Leslie Howard", "Merle Oberon", "Raymond Massey"],
            director: "Harold Young",
            year: 1934,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-39-steps-1935",
            title: "The 39 Steps",
            posterURL: "https://image.tmdb.org/t/p/w500/fL6u6LZhf8P3q1MKbYjQqiPjVcE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/fL6u6LZhf8P3q1MKbYjQqiPjVcE.jpg",
            overview: "A man wrongly accused of murder goes on the run while trying to uncover a spy ring. Hitchcock's legendary thriller that defined the genre!",
            releaseDate: "1935-06-06",
            runtime: 86,
            genre: [.thriller, .mystery, .adventure],
            rating: "PG",
            imdbRating: 7.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/The39Steps1935/The%2039%20Steps%20%281935%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=cNPLVhxnCKY",
            cast: ["Robert Donat", "Madeleine Carroll"],
            director: "Alfred Hitchcock",
            year: 1935,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-sabotage-1936",
            title: "Sabotage",
            posterURL: "https://image.tmdb.org/t/p/w500/9nLKGfgWJvMBvMNVXNUZMJyPbmT.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9nLKGfgWJvMBvMNVXNUZMJyPbmT.jpg",
            overview: "A Scotland Yard detective investigates a cinema owner suspected of being a terrorist saboteur. Hitchcock's dark masterpiece!",
            releaseDate: "1936-12-02",
            runtime: 76,
            genre: [.thriller, .crime, .drama],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/sabotage_1936/Sabotage.mp4",
            trailerURL: nil,
            cast: ["Sylvia Sidney", "Oscar Homolka", "Desmond Tester"],
            director: "Alfred Hitchcock",
            year: 1936,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-stranger-1946",
            title: "The Stranger",
            posterURL: "https://image.tmdb.org/t/p/w500/qjTdFBjWVKrH6xvCQmjGmJVKHvL.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qjTdFBjWVKrH6xvCQmjGmJVKHvL.jpg",
            overview: "A war crimes investigator tracks a Nazi hiding in a small Connecticut town. Orson Welles directs and stars in this gripping thriller!",
            releaseDate: "1946-07-02",
            runtime: 95,
            genre: [.thriller, .crime, .drama],
            rating: "PG",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheStranger_1946/The%20Stranger%20%281946%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=sYNQWZJzCpc",
            cast: ["Orson Welles", "Edward G. Robinson", "Loretta Young"],
            director: "Orson Welles",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        )
    ]

    // MARK: - Chunk 2
    static let _sampleMovies_chunk2: [FreeMovie] = [
        FreeMovie(
            id: "ia-kansas-city-confidential",
            title: "Kansas City Confidential",
            posterURL: "https://image.tmdb.org/t/p/w500/dQ7dG7lHBYwfHrMPBVKQHPjCLVK.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/dQ7dG7lHBYwfHrMPBVKQHPjCLVK.jpg",
            overview: "A man framed for robbery hunts down the real criminals to clear his name. Hard-boiled noir at its finest!",
            releaseDate: "1952-11-11",
            runtime: 99,
            genre: [.crime, .thriller, .drama],
            rating: "PG",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/KansasCityConfidential1952/Kansas%20City%20Confidential%20%281952%29.mp4",
            trailerURL: nil,
            cast: ["John Payne", "Coleen Gray", "Preston Foster"],
            director: "Phil Karlson",
            year: 1952,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
    ]
}
