import Foundation

extension FreeMovie {
    // MARK: Chunk 3
    static let _smc03: [FreeMovie] = [
        FreeMovie(
            id: "ia-the-hitch-hiker-1953",
            title: "The Hitch-Hiker",
            posterURL: "https://image.tmdb.org/t/p/w500/6PQ8KTsLhBVWMWQnJQDVUgvGqBe.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6PQ8KTsLhBVWMWQnJQDVUgvGqBe.jpg",
            overview: "Two fishermen pick up a hitchhiker who turns out to be a psychopathic killer. Intense noir thriller directed by Ida Lupino!",
            releaseDate: "1953-03-30",
            runtime: 71,
            genre: [.thriller, .crime],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheHitchHiker1953/The%20Hitch-Hiker%20%281953%29.mp4",
            trailerURL: nil,
            cast: ["Edmond O'Brien", "Frank Lovejoy", "William Talman"],
            director: "Ida Lupino",
            year: 1953,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-killing-1956",
            title: "The Killing",
            posterURL: "https://image.tmdb.org/t/p/w500/8hHrKJqNXPLnMVJPYxEwPBQiYVR.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8hHrKJqNXPLnMVJPYxEwPBQiYVR.jpg",
            overview: "A career criminal plans one final heist at a racetrack. Stanley Kubrick's breakthrough film that influenced Tarantino!",
            releaseDate: "1956-05-20",
            runtime: 84,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 8.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheKilling1956_201601/The%20Killing%20%281956%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=BYwCG9GXQXY",
            cast: ["Sterling Hayden", "Coleen Gray", "Vince Edwards"],
            director: "Stanley Kubrick",
            year: 1956,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎭 DRAMA MASTERPIECES - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-pygmalion-1938",
            title: "Pygmalion",
            posterURL: "https://image.tmdb.org/t/p/w500/gMv6fWTFJGPZpBqVhPfKLKEYEKX.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/gMv6fWTFJGPZpBqVhPfKLKEYEKX.jpg",
            overview: "A phonetics professor bets he can transform a Cockney flower girl into a lady. The film that inspired My Fair Lady!",
            releaseDate: "1938-10-06",
            runtime: 96,
            genre: [.comedy, .drama, .romance],
            rating: "G",
            imdbRating: 7.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Pygmalion1938/Pygmalion%20%281938%29.mp4",
            trailerURL: nil,
            cast: ["Leslie Howard", "Wendy Hiller"],
            director: "Anthony Asquith",
            year: 1938,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-lady-vanishes-1938",
            title: "The Lady Vanishes",
            posterURL: "https://image.tmdb.org/t/p/w500/fJmCL9YIqLGJQpGZhBJKfPKwQFT.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/fJmCL9YIqLGJQpGZhBJKfPKwQFT.jpg",
            overview: "On a train, a young woman discovers an elderly lady has disappeared and no one believes she existed. Hitchcock's witty mystery masterpiece!",
            releaseDate: "1938-10-07",
            runtime: 96,
            genre: [.mystery, .thriller, .comedy],
            rating: "G",
            imdbRating: 7.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLadyVanishes1938/The%20Lady%20Vanishes%20%281938%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=1wPgcCHqKEw",
            cast: ["Margaret Lockwood", "Michael Redgrave", "Dame May Whitty"],
            director: "Alfred Hitchcock",
            year: 1938,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-my-man-godfrey-1936",
            title: "My Man Godfrey",
            posterURL: "https://image.tmdb.org/t/p/w500/sGqJcqFqYAhVOvPvV3h7VLO4RhG.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/sGqJcqFqYAhVOvPvV3h7VLO4RhG.jpg",
            overview: "A socialite hires a homeless man as a butler, not knowing his true identity. Brilliant screwball comedy with William Powell!",
            releaseDate: "1936-09-06",
            runtime: 94,
            genre: [.comedy, .romance],
            rating: "G",
            imdbRating: 7.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/MyManGodfrey1936/My%20Man%20Godfrey%20%281936%29.mp4",
            trailerURL: nil,
            cast: ["William Powell", "Carole Lombard", "Alice Brady"],
            director: "Gregory La Cava",
            year: 1936,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-front-page-1931",
            title: "The Front Page",
            posterURL: "https://image.tmdb.org/t/p/w500/8GJ8vJCLPQGHSHPGOCjVQCGLqvN.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8GJ8vJCLPQGHSHPGOCjVQCGLqvN.jpg",
            overview: "A newspaper editor tries to keep his star reporter from leaving to get married when a big story breaks. Fast-talking pre-Code comedy!",
            releaseDate: "1931-03-13",
            runtime: 101,
            genre: [.comedy, .drama],
            rating: "G",
            imdbRating: 7.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheFrontPage1931/The%20Front%20Page%20%281931%29.mp4",
            trailerURL: nil,
            cast: ["Adolphe Menjou", "Pat O'Brien", "Mary Brian"],
            director: "Lewis Milestone",
            year: 1931,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-great-dictator-speech",
            title: "The Great Dictator (Final Speech)",
            posterURL: "https://image.tmdb.org/t/p/w500/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/1QpO9wo7JWecZ4NiBuu625FiY1j.jpg",
            overview: "Charlie Chaplin's powerful final speech from The Great Dictator - one of the most inspiring moments in cinema history!",
            releaseDate: "1940-10-15",
            runtime: 5,
            genre: [.drama],
            rating: "G",
            imdbRating: 8.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGreatDictatorSpeech/The%20Great%20Dictator%20Speech.mp4",
            trailerURL: "https://www.youtube.com/watch?v=J7GY1Xg6X20",
            cast: ["Charlie Chaplin"],
            director: "Charlie Chaplin",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-angel-on-my-shoulder-1946",
            title: "Angel on My Shoulder",
            posterURL: "https://image.tmdb.org/t/p/w500/3MvCvCfZJNFTqPNvxQTRpPJQvbH.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3MvCvCfZJNFTqPNvxQTRpPJQvbH.jpg",
            overview: "A dead gangster makes a deal with the Devil to return to Earth in the body of a judge. Fantasy noir with Paul Muni!",
            releaseDate: "1946-09-20",
            runtime: 101,
            genre: [.fantasy, .comedy, .drama],
            rating: "G",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AngelOnMyShoulder1946/Angel%20on%20My%20Shoulder%20%281946%29.mp4",
            trailerURL: nil,
            cast: ["Paul Muni", "Anne Baxter", "Claude Rains"],
            director: "Archie Mayo",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-man-who-knew-too-much-1934",
            title: "The Man Who Knew Too Much",
            posterURL: "https://image.tmdb.org/t/p/w500/qPZzQvPOJFLBXPVkLwqPSLzBFkT.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qPZzQvPOJFLBXPVkLwqPSLzBFkT.jpg",
            overview: "A couple's daughter is kidnapped to prevent them from revealing an assassination plot. Hitchcock's original thriller!",
            releaseDate: "1934-12-09",
            runtime: 75,
            genre: [.thriller, .mystery],
            rating: "PG",
            imdbRating: 6.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheManWhoKnewTooMuch1934/The%20Man%20Who%20Knew%20Too%20Much%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["Leslie Banks", "Edna Best", "Peter Lorre"],
            director: "Alfred Hitchcock",
            year: 1934,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        // ============================================
        // 🤠 WESTERN FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-angel-and-the-badman-1947",
            title: "Angel and the Badman",
            posterURL: "https://image.tmdb.org/t/p/w500/5xPWHNqBLQAZGJLKWQBIjGJYBvK.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/5xPWHNqBLQAZGJLKWQBIjGJYBvK.jpg",
            overview: "A wounded gunfighter is nursed back to health by a Quaker family and falls for their daughter. John Wayne's first film as producer!",
            releaseDate: "1947-02-15",
            runtime: 100,
            genre: [.western, .romance, .drama],
            rating: "G",
            imdbRating: 6.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AngelAndTheBadman1947/Angel%20and%20the%20Badman%20%281947%29.mp4",
            trailerURL: nil,
            cast: ["John Wayne", "Gail Russell", "Harry Carey"],
            director: "James Edward Grant",
            year: 1947,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-outlaw-1943",
            title: "The Outlaw",
            posterURL: "https://image.tmdb.org/t/p/w500/vUEXkSPKYAGC2u4CJPfFQXqNWCT.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/vUEXkSPKYAGC2u4CJPfFQXqNWCT.jpg",
            overview: "Billy the Kid, Doc Holliday, and Pat Garrett clash over a stolen horse and a beautiful woman. Howard Hughes' controversial Western!",
            releaseDate: "1943-02-05",
            runtime: 116,
            genre: [.western, .drama],
            rating: "PG",
            imdbRating: 5.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheOutlaw1943/The%20Outlaw%20%281943%29.mp4",
            trailerURL: nil,
            cast: ["Jack Buetel", "Jane Russell", "Thomas Mitchell", "Walter Huston"],
            director: "Howard Hughes",
            year: 1943,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-man-from-utah-1934",
            title: "The Man from Utah",
            posterURL: "https://image.tmdb.org/t/p/w500/qQhJHZ8vXQXLvLJPNcVQVYDMVwH.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qQhJHZ8vXQXLvLJPNcVQVYDMVwH.jpg",
            overview: "A young cowboy goes undercover to expose a crooked rodeo promoter. Early John Wayne action!",
            releaseDate: "1934-05-15",
            runtime: 55,
            genre: [.western, .action],
            rating: "G",
            imdbRating: 5.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheManFromUtah1934/The%20Man%20from%20Utah%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["John Wayne", "Polly Ann Young"],
            director: "Robert N. Bradbury",
            year: 1934,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-my-darling-clementine-extract",
            title: "My Darling Clementine",
            posterURL: "https://image.tmdb.org/t/p/w500/9P4Ux7FmFLFCmPkJQJLGJKxZVMr.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9P4Ux7FmFLFCmPkJQJLGJKxZVMr.jpg",
            overview: "Wyatt Earp and Doc Holliday face the Clanton gang at the O.K. Corral. John Ford's poetic Western masterpiece!",
            releaseDate: "1946-12-03",
            runtime: 97,
            genre: [.western, .drama],
            rating: "G",
            imdbRating: 7.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/MyDarlingClementine1946/My%20Darling%20Clementine%20%281946%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=RQfDUJxONrw",
            cast: ["Henry Fonda", "Linda Darnell", "Victor Mature"],
            director: "John Ford",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 😂 COMEDY CLASSICS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-gold-rush-1925",
            title: "The Gold Rush",
            posterURL: "https://image.tmdb.org/t/p/w500/eQRFo1qwRREYwj47Yoe1PisgOle.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/eQRFo1qwRREYwj47Yoe1PisgOle.jpg",
            overview: "The Tramp heads to the Klondike in search of gold. Features the legendary shoe-eating scene! Chaplin's masterpiece!",
            releaseDate: "1925-06-26",
            runtime: 95,
            genre: [.comedy, .adventure, .romance],
            rating: "G",
            imdbRating: 8.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CC_1925_06_26_TheGoldRush/CC_1925_06_26_TheGoldRush.mp4",
            trailerURL: "https://www.youtube.com/watch?v=bPO3lWBQEEY",
            cast: ["Charlie Chaplin", "Mack Swain", "Tom Murray"],
            director: "Charlie Chaplin",
            year: 1925,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-city-lights-1931",
            title: "City Lights",
            posterURL: "https://image.tmdb.org/t/p/w500/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bXNvzjULc9jrOVhGfjcc64uKZmZ.jpg",
            overview: "The Tramp falls for a blind flower girl and tries to raise money for her sight-restoring operation. One of the greatest films ever made!",
            releaseDate: "1931-01-30",
            runtime: 87,
            genre: [.comedy, .drama, .romance],
            rating: "G",
            imdbRating: 8.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CityLights1931/City%20Lights%20%281931%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=7vl7F8S4cpQ",
            cast: ["Charlie Chaplin", "Virginia Cherrill", "Florence Lee"],
            director: "Charlie Chaplin",
            year: 1931,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-safety-last-1923",
            title: "Safety Last!",
            posterURL: "https://image.tmdb.org/t/p/w500/vT6VhpjHcvPg1xvCT1iUfPLvGiC.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/vT6VhpjHcvPg1xvCT1iUfPLvGiC.jpg",
            overview: "A young man climbs a skyscraper to win a cash prize. Features the iconic clock-hanging scene! Harold Lloyd's most famous film!",
            releaseDate: "1923-04-01",
            runtime: 70,
            genre: [.comedy, .action],
            rating: "G",
            imdbRating: 8.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/SafetyLast1923/Safety%20Last%21%20%281923%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=VBBskvPxzZM",
            cast: ["Harold Lloyd", "Mildred Davis", "Bill Strother"],
            director: "Fred C. Newmeyer",
            year: 1923,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-kid-1921",
            title: "The Kid",
            posterURL: "https://image.tmdb.org/t/p/w500/dhjrHGdKhZLLqNrY5UQYO1V2XYv.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/dhjrHGdKhZLLqNrY5UQYO1V2XYv.jpg",
            overview: "The Tramp raises an abandoned child as his own. Chaplin's first feature-length film - a perfect blend of comedy and drama!",
            releaseDate: "1921-01-21",
            runtime: 68,
            genre: [.comedy, .drama, .family],
            rating: "G",
            imdbRating: 8.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CC_1921_02_06_TheKid/CC_1921_02_06_TheKid.mp4",
            trailerURL: "https://www.youtube.com/watch?v=Pe8hMqsqtJE",
            cast: ["Charlie Chaplin", "Jackie Coogan", "Edna Purviance"],
            director: "Charlie Chaplin",
            year: 1921,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-sherlock-jr-1924",
            title: "Sherlock Jr.",
            posterURL: "https://image.tmdb.org/t/p/w500/bBQRhWHBoGJCVQhvJCVFVPvHuKs.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bBQRhWHBoGJCVQhvJCVFVPvHuKs.jpg",
            overview: "A film projectionist dreams of being a detective and enters the movie screen. Buster Keaton's surreal comedy masterpiece!",
            releaseDate: "1924-04-21",
            runtime: 45,
            genre: [.comedy, .romance],
            rating: "G",
            imdbRating: 8.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/SherlockJr.1924/Sherlock%20Jr.%20%281924%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=Vxr5dIL7LCk",
            cast: ["Buster Keaton", "Kathryn McGuire", "Joe Keaton"],
            director: "Buster Keaton",
            year: 1924,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-cameraman-1928",
            title: "The Cameraman",
            posterURL: "https://image.tmdb.org/t/p/w500/dMsNqPJNBYGzYJAGcJLHLQCLHqE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/dMsNqPJNBYGzYJAGcJLHLQCLHqE.jpg",
            overview: "A tintype photographer tries to become a newsreel cameraman to impress a woman. Buster Keaton's hilarious silent classic!",
            releaseDate: "1928-09-22",
            runtime: 69,
            genre: [.comedy, .romance],
            rating: "G",
            imdbRating: 8.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheCameraman1928/The%20Cameraman%20%281928%29.mp4",
            trailerURL: nil,
            cast: ["Buster Keaton", "Marceline Day", "Harold Goodwin"],
            director: "Edward Sedgwick",
            year: 1928,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-topper-1937",
            title: "Topper",
            posterURL: "https://image.tmdb.org/t/p/w500/hxqKvOkLVJLsLAJVPKqMjQUzqSw.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/hxqKvOkLVJLsLAJVPKqMjQUzqSw.jpg",
            overview: "A stuffy banker's life is turned upside down by two fun-loving ghosts. Cary Grant comedy classic!",
            releaseDate: "1937-07-16",
            runtime: 97,
            genre: [.comedy, .fantasy, .romance],
            rating: "G",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Topper1937/Topper%20%281937%29.mp4",
            trailerURL: nil,
            cast: ["Cary Grant", "Constance Bennett", "Roland Young"],
            director: "Norman Z. McLeod",
            year: 1937,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🌙 FILM NOIR ESSENTIALS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-scarlet-street-1945",
            title: "Scarlet Street",
            posterURL: "https://image.tmdb.org/t/p/w500/m7pPqJLJKLJqQHFLCJHvLPKLqHE.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/m7pPqJLJKLJqQHFLCJHvLPKLqHE.jpg",
            overview: "A meek cashier falls for a femme fatale who manipulates him into crime. Fritz Lang's dark noir masterpiece!",
            releaseDate: "1945-12-28",
            runtime: 102,
            genre: [.crime, .drama, .thriller],
            rating: "PG",
            imdbRating: 7.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ScarletStreet1945/Scarlet%20Street%20%281945%29.mp4",
            trailerURL: nil,
            cast: ["Edward G. Robinson", "Joan Bennett", "Dan Duryea"],
            director: "Fritz Lang",
            year: 1945,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
    ]
}
