import Foundation

extension FreeMovie {
    // MARK: Chunk 8
    static let _smc08: [FreeMovie] = [
        FreeMovie(
            id: "ia-a-midsummer-nights-dream-1935",
            title: "A Midsummer Night's Dream",
            posterURL: "https://image.tmdb.org/t/p/w500/aLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/aLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Fairies meddle in the love lives of mortals in Shakespeare's enchanted forest. Hollywood's lavish 1935 adaptation!",
            releaseDate: "1935-10-07",
            runtime: 132,
            genre: [.fantasy, .comedy, .romance],
            rating: "G",
            imdbRating: 6.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AMidsummerNightsDream1935/A%20Midsummer%20Night%27s%20Dream%20%281935%29.mp4",
            trailerURL: nil,
            cast: ["James Cagney", "Dick Powell", "Olivia de Havilland"],
            director: "William Dieterle",
            year: 1935,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-thief-of-bagdad-1940-trailer",
            title: "The Thief of Bagdad (1940 Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/bLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A blind prince and a thief quest to defeat an evil sorcerer. One of the greatest fantasy films ever made!",
            releaseDate: "1940-12-19",
            runtime: 4,
            genre: [.fantasy, .adventure, .romance],
            rating: "G",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheThiefOfBagdad1940Trailer/The%20Thief%20of%20Bagdad%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=G9Xz7fL5h3k",
            cast: ["Sabu", "Conrad Veidt", "June Duprez"],
            director: "Ludwig Berger",
            year: 1940,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-jack-and-the-beanstalk-1952",
            title: "Jack and the Beanstalk",
            posterURL: "https://image.tmdb.org/t/p/w500/cLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/cLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Jack climbs the beanstalk to rescue a princess from a giant. Abbott & Costello's hilarious fairy tale adventure!",
            releaseDate: "1952-04-04",
            runtime: 76,
            genre: [.comedy, .fantasy, .family],
            rating: "G",
            imdbRating: 6.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/JackAndTheBeanstalk1952/Jack%20and%20the%20Beanstalk%20%281952%29.mp4",
            trailerURL: nil,
            cast: ["Bud Abbott", "Lou Costello"],
            director: "Jean Yarbrough",
            year: 1952,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-one-million-bc-1940",
            title: "One Million B.C.",
            posterURL: "https://image.tmdb.org/t/p/w500/dLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/dLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Cave people battle dinosaurs and rival tribes in the Stone Age. The original prehistoric adventure that inspired the remake!",
            releaseDate: "1940-04-05",
            runtime: 79,
            genre: [.adventure, .fantasy, .romance],
            rating: "PG",
            imdbRating: 5.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/OneMillionBC1940/One%20Million%20B.C.%20%281940%29.mp4",
            trailerURL: nil,
            cast: ["Victor Mature", "Carole Landis", "Lon Chaney Jr."],
            director: "Hal Roach",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎨 MORE ANIMATION - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "blender-cosmos-laundromat",
            title: "Cosmos Laundromat",
            posterURL: "https://i.ytimg.com/vi/Y-rh20l_2J4/hqdefault.jpg",
            backdropURL: "https://archive.org/services/img/CosmosLaundromat2015",
            overview: "A depressed sheep on a desert island gets a chance to relive his life. Blender's stunning philosophical animation!",
            releaseDate: "2015-01-26",
            runtime: 12,
            genre: [.animation, .fantasy, .drama],
            rating: "G",
            imdbRating: 6.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CosmosLaundromat2015/Cosmos%20Laundromat.mp4",
            trailerURL: "https://www.youtube.com/watch?v=Y-rh20l_2J4",
            cast: [],
            director: "Mathieu Auvray",
            year: 2015,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "blender-spring-2019",
            title: "Spring",
            posterURL: "https://i.ytimg.com/vi/WhWc3b3KhnY/hqdefault.jpg",
            backdropURL: "https://archive.org/services/img/Spring2019Blender",
            overview: "A shepherd girl and her dog face ancient spirits in a changing world. Blender's breathtaking 2019 open movie!",
            releaseDate: "2019-04-03",
            runtime: 8,
            genre: [.animation, .fantasy],
            rating: "G",
            imdbRating: 6.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Spring2019Blender/Spring.mp4",
            trailerURL: "https://www.youtube.com/watch?v=WhWc3b3KhnY",
            cast: [],
            director: "Andy Goralczyk",
            year: 2019,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "blender-agent-327",
            title: "Agent 327: Operation Barbershop",
            posterURL: "https://i.ytimg.com/vi/mI9fFMgeCPo/hqdefault.jpg",
            backdropURL: "https://archive.org/services/img/Agent327OperationBarbershop2017",
            overview: "A secret agent battles a villain in a barbershop. Blender's action-packed animation test that became a hit!",
            releaseDate: "2017-05-15",
            runtime: 4,
            genre: [.animation, .action, .comedy],
            rating: "G",
            imdbRating: 6.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Agent327OperationBarbershop2017/Agent%20327%20-%20Operation%20Barbershop.mp4",
            trailerURL: "https://www.youtube.com/watch?v=mI9fFMgeCPo",
            cast: [],
            director: "Colin Levy",
            year: 2017,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "blender-hero-2018",
            title: "Hero",
            posterURL: "https://i.ytimg.com/vi/p0kzwQ1K3os/hqdefault.jpg",
            backdropURL: "https://archive.org/services/img/Hero2018Blender",
            overview: "A martial artist must choose between his honor and his life. Blender's stunning grease pencil animation!",
            releaseDate: "2018-02-24",
            runtime: 3,
            genre: [.animation, .action],
            rating: "G",
            imdbRating: 6.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Hero2018Blender/Hero.mp4",
            trailerURL: "https://www.youtube.com/watch?v=p0kzwQ1K3os",
            cast: [],
            director: "Daniel M. Lara",
            year: 2018,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        // ============================================
        // 🎪 CULT CLASSICS & B-MOVIES - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-thing-from-another-world-1951-trailer",
            title: "The Thing from Another World (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/eLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/eLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Scientists in the Arctic battle a bloodthirsty alien invader. The original that inspired John Carpenter's remake!",
            releaseDate: "1951-04-06",
            runtime: 3,
            genre: [.scifi, .horror, .thriller],
            rating: "PG",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheThingFromAnotherWorld1951Trailer/The%20Thing%20from%20Another%20World%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=F6tNkXM6bJQ",
            cast: ["James Arness", "Margaret Sheridan", "Kenneth Tobey"],
            director: "Christian Nyby",
            year: 1951,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-fly-1958-trailer",
            title: "The Fly (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/fLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/fLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A scientist's teleportation experiment goes horribly wrong, merging him with a fly. The classic sci-fi horror trailer!",
            releaseDate: "1958-06-16",
            runtime: 3,
            genre: [.scifi, .horror],
            rating: "PG",
            imdbRating: 7.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheFly1958Trailer/The%20Fly%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=G4N1m3PTmOY",
            cast: ["Vincent Price", "David Hedison", "Patricia Owens"],
            director: "Kurt Neumann",
            year: 1958,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-invasion-of-the-body-snatchers-1956-trailer",
            title: "Invasion of the Body Snatchers (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/gLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/gLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Alien pods replace humans with emotionless duplicates. The McCarthy-era sci-fi classic that still terrifies!",
            releaseDate: "1956-02-05",
            runtime: 3,
            genre: [.scifi, .horror, .thriller],
            rating: "PG",
            imdbRating: 7.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/InvasionOfTheBodySnatchers1956Trailer/Invasion%20of%20the%20Body%20Snatchers%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=CFnBzG0rKJo",
            cast: ["Kevin McCarthy", "Dana Wynter", "Larry Gates"],
            director: "Don Siegel",
            year: 1956,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-wasp-woman-1959",
            title: "The Wasp Woman",
            posterURL: "https://image.tmdb.org/t/p/w500/hLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/hLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A cosmetics executive uses wasp enzymes to stay young, with terrifying results. Roger Corman's campy creature feature!",
            releaseDate: "1959-10-11",
            runtime: 66,
            genre: [.horror, .scifi],
            rating: "PG",
            imdbRating: 4.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheWaspWoman1959/The%20Wasp%20Woman%20%281959%29.mp4",
            trailerURL: nil,
            cast: ["Susan Cabot", "Anthony Eisley", "Barboura Morris"],
            director: "Roger Corman",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-brain-that-wouldnt-die-1962-alt",
            title: "The Brain That Wouldn't Die",
            posterURL: "https://image.tmdb.org/t/p/w500/iLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/iLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A surgeon keeps his fiancée's head alive while searching for a new body. So bad it's great! Classic B-movie horror!",
            releaseDate: "1962-05-14",
            runtime: 82,
            genre: [.horror, .scifi],
            rating: "PG",
            imdbRating: 4.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheBrainThatWouldntDie1962/The%20Brain%20That%20Wouldn%27t%20Die%20%281962%29.mp4",
            trailerURL: nil,
            cast: ["Jason Evers", "Virginia Leith", "Anthony La Penna"],
            director: "Joseph Green",
            year: 1962,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-atomic-brain-1964",
            title: "The Atomic Brain",
            posterURL: "https://image.tmdb.org/t/p/w500/jLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/jLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A mad scientist transplants brains between bodies in his quest for immortality. Creepy 60s sci-fi horror!",
            releaseDate: "1964-01-01",
            runtime: 64,
            genre: [.scifi, .horror],
            rating: "PG",
            imdbRating: 3.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheAtomicBrain1964/The%20Atomic%20Brain%20%281964%29.mp4",
            trailerURL: nil,
            cast: ["Frank Gerstle", "Margaret Hamilton", "Kenne Duncan"],
            director: "Joseph Mascelli",
            year: 1964,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-giant-gila-monster-1959",
            title: "The Giant Gila Monster",
            posterURL: "https://image.tmdb.org/t/p/w500/kLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/kLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A giant lizard terrorizes a small Texas town. 50s drive-in creature feature with hot rods and rock 'n' roll!",
            releaseDate: "1959-06-01",
            runtime: 108,
            genre: [.horror, .scifi],
            rating: "PG",
            imdbRating: 3.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGiantGilaMonster1959/The%20Giant%20Gila%20Monster%20%281959%29.mp4",
            trailerURL: nil,
            cast: ["Don Sullivan", "Fred Graham", "Lisa Simone"],
            director: "Ray Kellogg",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-killer-shrews-1959",
            title: "The Killer Shrews",
            posterURL: "https://image.tmdb.org/t/p/w500/lLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/lLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Scientists on an island create giant venomous shrews that escape and hunt humans. Classic 50s creature feature!",
            releaseDate: "1959-06-01",
            runtime: 69,
            genre: [.horror, .scifi, .thriller],
            rating: "PG",
            imdbRating: 3.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheKillerShrews1959/The%20Killer%20Shrews%20%281959%29.mp4",
            trailerURL: nil,
            cast: ["James Best", "Ingrid Goude", "Ken Curtis"],
            director: "Ray Kellogg",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-phantom-creeps-1939",
            title: "The Phantom Creeps",
            posterURL: "https://image.tmdb.org/t/p/w500/mLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/mLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A mad scientist creates a robot and a deadly gas to conquer the world. Bela Lugosi serial adventure!",
            releaseDate: "1939-01-15",
            runtime: 256,
            genre: [.scifi, .horror, .action],
            rating: "PG",
            imdbRating: 5.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePhantomCreeps1939/The%20Phantom%20Creeps%20%281939%29.mp4",
            trailerURL: nil,
            cast: ["Bela Lugosi", "Dorothy Arnold", "Robert Kent"],
            director: "Ford Beebe",
            year: 1939,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-king-of-the-zombies-1941",
            title: "King of the Zombies",
            posterURL: "https://image.tmdb.org/t/p/w500/nLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/nLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A pilot and his passengers crash on a Caribbean island ruled by a voodoo doctor. WWII zombie horror comedy!",
            releaseDate: "1941-07-30",
            runtime: 67,
            genre: [.horror, .comedy, .war],
            rating: "PG",
            imdbRating: 5.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/KingOfTheZombies1941/King%20of%20the%20Zombies%20%281941%29.mp4",
            trailerURL: nil,
            cast: ["Dick Purcell", "Joan Woodbury", "Mantan Moreland"],
            director: "Jean Yarbrough",
            year: 1941,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-revolt-of-the-zombies-1936",
            title: "Revolt of the Zombies",
            posterURL: "https://image.tmdb.org/t/p/w500/oLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/oLJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A priest uses an ancient formula to create a zombie army in the Cambodian jungle. Pre-Code zombie horror!",
            releaseDate: "1936-06-03",
            runtime: 65,
            genre: [.horror, .scifi],
            rating: "PG",
            imdbRating: 3.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/RevoltOfTheZombies1936/Revolt%20of%20the%20Zombies%20%281936%29.mp4",
            trailerURL: nil,
            cast: ["Dorothy Stone", "Dean Jagger", "Roy D'Arcy"],
            director: "Victor Halperin",
            year: 1936,
            language: "English",
            country: "US",
            isAvailable: true
        )
    ]
}
