import Foundation

extension FreeMovie {
    // MARK: Chunk 6
    static let _smc06: [FreeMovie] = [
        FreeMovie(
            id: "ia-west-of-the-divide-1934",
            title: "West of the Divide",
            posterURL: "https://image.tmdb.org/t/p/w500/yLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/yLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A man searches for his missing brother and the killer who murdered their father. John Wayne in a classic western!",
            releaseDate: "1934-02-15",
            runtime: 55,
            genre: [.western, .action],
            rating: "G",
            imdbRating: 5.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/WestOfTheDivide1934/West%20of%20the%20Divide%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["John Wayne", "Virginia Brown Faire", "George Hayes"],
            director: "Robert N. Bradbury",
            year: 1934,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 💕 ROMANCE & SWASHBUCKLER - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-robin-hood-1922",
            title: "Robin Hood",
            posterURL: "https://image.tmdb.org/t/p/w500/7LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/7LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "The Earl of Huntingdon returns from the Crusades as Robin Hood to fight the tyrannical Prince John. Douglas Fairbanks' epic adventure!",
            releaseDate: "1922-10-18",
            runtime: 127,
            genre: [.adventure, .action, .romance],
            rating: "G",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/RobinHood1922/Robin%20Hood%20%281922%29.mp4",
            trailerURL: nil,
            cast: ["Douglas Fairbanks", "Enid Bennett", "Paul Dickey"],
            director: "Allan Dwan",
            year: 1922,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-sheik-1921",
            title: "The Sheik",
            posterURL: "https://image.tmdb.org/t/p/w500/8LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A desert chieftain kidnaps an English aristocrat and a clash of cultures turns to passion. Rudolph Valentino's iconic role!",
            releaseDate: "1921-11-06",
            runtime: 86,
            genre: [.romance, .adventure, .drama],
            rating: "G",
            imdbRating: 6.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheSheik1921/The%20Sheik%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Rudolph Valentino", "Agnes Ayres", "Ruth Miller"],
            director: "George Melford",
            year: 1921,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-blood-and-sand-1922",
            title: "Blood and Sand",
            posterURL: "https://image.tmdb.org/t/p/w500/9LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A poor boy rises to become Spain's greatest matador, but a seductive aristocrat leads to his downfall. Valentino's passionate drama!",
            releaseDate: "1922-11-05",
            runtime: 79,
            genre: [.drama, .romance],
            rating: "G",
            imdbRating: 6.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/BloodAndSand1922/Blood%20and%20Sand%20%281922%29.mp4",
            trailerURL: nil,
            cast: ["Rudolph Valentino", "Lila Lee", "Rosa Rosanova"],
            director: "Fred Niblo",
            year: 1922,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-birth-of-a-nation-trailer",
            title: "The Birth of a Nation (Excerpt)",
            posterURL: "https://image.tmdb.org/t/p/w500/0LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/0LJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "D.W. Griffith's landmark Civil War epic that revolutionized cinema technique. A historically significant but controversial film.",
            releaseDate: "1915-02-08",
            runtime: 15,
            genre: [.drama, .war, .romance],
            rating: "G",
            imdbRating: 6.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/BirthOfANationExcerpt/Birth%20of%20a%20Nation%20-%20Excerpt.mp4",
            trailerURL: nil,
            cast: ["Lillian Gish", "Mae Marsh", "Henry B. Walthall"],
            director: "D.W. Griffith",
            year: 1915,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-intolerance-1916",
            title: "Intolerance",
            posterURL: "https://image.tmdb.org/t/p/w500/aLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/aLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "Four stories of intolerance across the ages, from Babylon to modern America. Griffith's cinematic spectacle!",
            releaseDate: "1916-09-05",
            runtime: 178,
            genre: [.drama, .war, .romance],
            rating: "G",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Intolerance1916/Intolerance%20%281916%29.mp4",
            trailerURL: nil,
            cast: ["Lillian Gish", "Mae Marsh", "Constance Talmadge"],
            director: "D.W. Griffith",
            year: 1916,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 😂 MORE COMEDY - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-son-of-the-sheik-1926",
            title: "The Son of the Sheik",
            posterURL: "https://image.tmdb.org/t/p/w500/bLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "The Sheik's son falls for a dancing girl but is betrayed by her father's gang. Valentino's final and best film!",
            releaseDate: "1926-09-05",
            runtime: 68,
            genre: [.adventure, .romance, .drama],
            rating: "G",
            imdbRating: 7.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheSonOfTheSheik1926/The%20Son%20of%20the%20Sheik%20%281926%29.mp4",
            trailerURL: nil,
            cast: ["Rudolph Valentino", "Vilma Bánky"],
            director: "George Fitzmaurice",
            year: 1926,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-nut-1921",
            title: "The Nut",
            posterURL: "https://image.tmdb.org/t/p/w500/cLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/cLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "An eccentric inventor tries to win over a social worker with his wild gadgets. Douglas Fairbanks comedy!",
            releaseDate: "1921-11-06",
            runtime: 79,
            genre: [.comedy, .romance],
            rating: "G",
            imdbRating: 5.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheNut1921/The%20Nut%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Douglas Fairbanks", "Marguerite De La Motte"],
            director: "Theodore Reed",
            year: 1921,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-goat-1921",
            title: "The Goat",
            posterURL: "https://image.tmdb.org/t/p/w500/dLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/dLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A man is mistaken for a notorious criminal and goes on the run. Buster Keaton's hilarious chase comedy!",
            releaseDate: "1921-05-23",
            runtime: 23,
            genre: [.comedy, .action],
            rating: "G",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGoat1921/The%20Goat%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Buster Keaton", "Virginia Fox"],
            director: "Buster Keaton",
            year: 1921,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-play-house-1921",
            title: "The Play House",
            posterURL: "https://image.tmdb.org/t/p/w500/eLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/eLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "Keaton plays every role in a theater — audience, orchestra, performers — in this mind-bending comedy classic!",
            releaseDate: "1921-10-06",
            runtime: 22,
            genre: [.comedy],
            rating: "G",
            imdbRating: 7.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePlayHouse1921/The%20Play%20House%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Buster Keaton", "Virginia Fox"],
            director: "Buster Keaton",
            year: 1921,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-hard-luck-1921",
            title: "Hard Luck",
            posterURL: "https://image.tmdb.org/t/p/w500/fLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/fLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "Down on his luck, a man tries various schemes to get ahead. Features Keaton's most famous stunt ending!",
            releaseDate: "1921-03-14",
            runtime: 22,
            genre: [.comedy],
            rating: "G",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/HardLuck1921/Hard%20Luck%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Buster Keaton", "Virginia Fox"],
            director: "Buster Keaton",
            year: 1921,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🚀 MORE SCI-FI - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-atomic-city-1952",
            title: "The Atomic City",
            posterURL: "https://image.tmdb.org/t/p/w500/gLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/gLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "The son of a nuclear scientist is kidnapped by enemy agents. Cold War thriller set in Los Alamos!",
            releaseDate: "1952-05-23",
            runtime: 85,
            genre: [.thriller, .drama],
            rating: "PG",
            imdbRating: 6.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheAtomicCity1952/The%20Atomic%20City%20%281952%29.mp4",
            trailerURL: nil,
            cast: ["Gene Barry", "Lydia Clarke", "Milburn Stone"],
            director: "Jerry Hopper",
            year: 1952,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-man-with-the-x-ray-eyes",
            title: "X: The Man with the X-Ray Eyes",
            posterURL: "https://image.tmdb.org/t/p/w500/hLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/hLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A doctor develops eye drops that give him x-ray vision, but the power grows beyond his control. Roger Corman's trippy sci-fi!",
            releaseDate: "1963-09-18",
            runtime: 79,
            genre: [.scifi, .horror],
            rating: "PG",
            imdbRating: 6.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/XTheManWithTheXrayEyes1963/X%20-%20The%20Man%20with%20the%20X-Ray%20Eyes%20%281963%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=7iJrF8E2VfY",
            cast: ["Ray Milland", "Diana Van der Vlis", "Harold J. Stone"],
            director: "Roger Corman",
            year: 1963,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-phantom-planet-1961",
            title: "The Phantom Planet",
            posterURL: "https://image.tmdb.org/t/p/w500/iLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/iLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "An astronaut crashes on an asteroid and shrinks to the size of its tiny inhabitants. Classic 60s space adventure!",
            releaseDate: "1961-12-01",
            runtime: 82,
            genre: [.scifi, .adventure],
            rating: "G",
            imdbRating: 3.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePhantomPlanet1961/The%20Phantom%20Planet%20%281961%29.mp4",
            trailerURL: nil,
            cast: ["Dean Fredericks", "Coleen Gray", "Anthony Dexter"],
            director: "William Marshall",
            year: 1961,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-first-spaceship-on-venus-1962",
            title: "First Spaceship on Venus",
            posterURL: "https://image.tmdb.org/t/p/w500/jLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/jLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "An international crew travels to Venus to investigate an alien artifact. East German/Polish sci-fi epic!",
            releaseDate: "1962-03-15",
            runtime: 80,
            genre: [.scifi, .adventure],
            rating: "G",
            imdbRating: 4.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/FirstSpaceshipOnVenus1962/First%20Spaceship%20on%20Venus%20%281962%29.mp4",
            trailerURL: nil,
            cast: ["Yoko Tani", "Oldrich Lukes", "Ingmar Kinsky"],
            director: "Kurt Maetzig",
            year: 1962,
            language: "English",
            country: "DE",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-assignment-outer-space-1960",
            title: "Assignment Outer Space",
            posterURL: "https://image.tmdb.org/t/p/w500/kLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/kLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A reporter on a space station must stop an out-of-control satellite from destroying Earth. Italian space opera!",
            releaseDate: "1960-12-01",
            runtime: 79,
            genre: [.scifi, .adventure],
            rating: "G",
            imdbRating: 4.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AssignmentOuterSpace1960/Assignment%20Outer%20Space%20%281960%29.mp4",
            trailerURL: nil,
            cast: ["Rick Van Nutter", "Gabriella Farinon", "David Maraniss"],
            director: "Antonio Margheriti",
            year: 1960,
            language: "English",
            country: "IT",
            isAvailable: true
        ),
        
        // ============================================
        // 🔍 MORE CRIME NOIR - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-hitch-hiker-1953-noir",
            title: "The Hitch-Hiker (Noir)",
            posterURL: "https://image.tmdb.org/t/p/w500/6PQ8KTsLhBVWMWQnJQDVUgvGqBe.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6PQ8KTsLhBVWMWQnJQDVUgvGqBe.jpg",
            overview: "Two fishermen pick up a hitchhiker who turns out to be a psychopathic killer. Ida Lupino's intense noir!",
            releaseDate: "1953-03-30",
            runtime: 71,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheHitchHiker1953Noir/The%20Hitch-Hiker%20%281953%29.mp4",
            trailerURL: nil,
            cast: ["Edmond O'Brien", "Frank Lovejoy", "William Talman"],
            director: "Ida Lupino",
            year: 1953,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-quicksand-1950",
            title: "Quicksand",
            posterURL: "https://image.tmdb.org/t/p/w500/lLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/lLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "An auto mechanic's petty theft spirals into increasingly desperate crimes. Mickey Rooney in a dark noir!",
            releaseDate: "1950-06-15",
            runtime: 79,
            genre: [.crime, .thriller, .drama],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Quicksand1950/Quicksand%20%281950%29.mp4",
            trailerURL: nil,
            cast: ["Mickey Rooney", "Jeanne Cagney", "Barbara Bates"],
            director: "Irving Pichel",
            year: 1950,
            language: "English",
            country: "US",
            isAvailable: true
        )
    ]

    // MARK: - Chunk 4
    static let _sampleMovies_chunk4: [FreeMovie] = [
        FreeMovie(
            id: "ia-the-long-night-1947",
            title: "The Long Night",
            posterURL: "https://image.tmdb.org/t/p/w500/mLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/mLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A veteran kills a man in self-defense and relives the events that led to the confrontation. Henry Fonda noir!",
            releaseDate: "1947-07-16",
            runtime: 101,
            genre: [.crime, .drama, .thriller],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLongNight1947/The%20Long%20Night%20%281947%29.mp4",
            trailerURL: nil,
            cast: ["Henry Fonda", "Barbara Bel Geddes", "Vincent Price"],
            director: "Anatole Litvak",
            year: 1947,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-tension-1949",
            title: "Tension",
            posterURL: "https://image.tmdb.org/t/p/w500/nLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/nLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A meek pharmacist plots to murder his cheating wife's lover, but someone else commits the crime first. Twisty noir!",
            releaseDate: "1949-06-24",
            runtime: 95,
            genre: [.crime, .thriller, .drama],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Tension1949/Tension%20%281949%29.mp4",
            trailerURL: nil,
            cast: ["Richard Basehart", "Audrey Totter", "Cyd Charisse"],
            director: "John Berry",
            year: 1949,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-pit-and-the-pendulum-1961",
            title: "The Pit and the Pendulum",
            posterURL: "https://image.tmdb.org/t/p/w500/oLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/oLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A man investigates his brother's death in a haunted castle with a deadly pendulum. Vincent Price in Poe adaptation!",
            releaseDate: "1961-08-12",
            runtime: 80,
            genre: [.horror, .mystery, .thriller],
            rating: "PG",
            imdbRating: 6.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePitAndThePendulum1961/The%20Pit%20and%20the%20Pendulum%20%281961%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=3qLb2F9XnEg",
            cast: ["Vincent Price", "John Kerr", "Barbara Steele"],
            director: "Roger Corman",
            year: 1961,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
    ]
}
