import Foundation

extension FreeMovie {
    // MARK: Chunk 7
    static let _smc07: [FreeMovie] = [
        FreeMovie(
            id: "ia-house-on-haunted-hill-1959-alt",
            title: "House on Haunted Hill",
            posterURL: "https://image.tmdb.org/t/p/w500/pLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/pLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "An eccentric millionaire offers $10,000 to anyone who survives a night in his haunted house. Vincent Price horror classic!",
            releaseDate: "1959-10-28",
            runtime: 75,
            genre: [.horror, .mystery, .thriller],
            rating: "PG",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/HouseOnHauntedHill1959/House%20on%20Haunted%20Hill%20%281959%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=ZvLJ5fDXqJU",
            cast: ["Vincent Price", "Carol Ohmart", "Richard Long"],
            director: "William Castle",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🗺️ ADVENTURE - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-captain-blood-1935-trailer",
            title: "Captain Blood (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/qLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "A doctor sold into slavery becomes a daring pirate captain. Errol Flynn's swashbuckling debut!",
            releaseDate: "1935-12-28",
            runtime: 4,
            genre: [.adventure, .action, .romance],
            rating: "PG",
            imdbRating: 7.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CaptainBlood1935Trailer/Captain%20Blood%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=8c3mJqJjF8Y",
            cast: ["Errol Flynn", "Olivia de Havilland", "Basil Rathbone"],
            director: "Michael Curtiz",
            year: 1935,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-scarlet-pimpernel-1934-alt",
            title: "The Scarlet Pimpernel (Alternate)",
            posterURL: "https://image.tmdb.org/t/p/w500/rLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/rLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "A dashing English nobleman rescues French aristocrats from the guillotine. Leslie Howard's classic adventure!",
            releaseDate: "1934-12-01",
            runtime: 97,
            genre: [.adventure, .romance, .drama],
            rating: "G",
            imdbRating: 7.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheScarletPimpernel1934Alt/The%20Scarlet%20Pimpernel%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["Leslie Howard", "Merle Oberon", "Raymond Massey"],
            director: "Harold Young",
            year: 1934,
            language: "English",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-adventures-of-robin-hood-1938-trailer",
            title: "The Adventures of Robin Hood (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/sLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/sLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "Robin Hood fights against the tyrannical Prince John and the Sheriff of Nottingham. Errol Flynn's definitive adventure!",
            releaseDate: "1938-05-06",
            runtime: 4,
            genre: [.adventure, .action, .romance],
            rating: "G",
            imdbRating: 8.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AdventuresOfRobinHood1938Trailer/The%20Adventures%20of%20Robin%20Hood%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=8c3mJqJjF8Y",
            cast: ["Errol Flynn", "Olivia de Havilland", "Basil Rathbone"],
            director: "Michael Curtiz",
            year: 1938,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-treasure-island-1950-trailer",
            title: "Treasure Island (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/tLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/tLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "A boy and a pirate search for buried treasure on a mysterious island. Robert Newton's legendary Long John Silver!",
            releaseDate: "1950-07-19",
            runtime: 3,
            genre: [.adventure, .family],
            rating: "G",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TreasureIsland1950Trailer/Treasure%20Island%20-%20Trailer.mp4",
            trailerURL: nil,
            cast: ["Robert Newton", "Bobby Driscoll"],
            director: "Byron Haskin",
            year: 1950,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-most-dangerous-game-1932",
            title: "The Most Dangerous Game",
            posterURL: "https://image.tmdb.org/t/p/w500/uLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/uLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "A mad count hunts shipwrecked sailors on his private island for sport. The original survival thriller that inspired them all!",
            releaseDate: "1932-09-09",
            runtime: 63,
            genre: [.adventure, .thriller, .horror],
            rating: "PG",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheMostDangerousGame1932/The%20Most%20Dangerous%20Game%20%281932%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=XfHDo8XGzRQ",
            cast: ["Joel McCrea", "Fay Wray", "Leslie Banks"],
            director: "Irving Pichel",
            year: 1932,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 📽️ DOCUMENTARY & SPECIAL - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-nanook-of-the-north-1922",
            title: "Nanook of the North",
            posterURL: "https://image.tmdb.org/t/p/w500/vLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/vLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "An Inuit family's struggle for survival in the harsh Arctic. The first feature-length documentary ever made!",
            releaseDate: "1922-06-11",
            runtime: 79,
            genre: [.documentary, .drama],
            rating: "G",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/NanookOfTheNorth1922/Nanook%20of%20the%20North%20%281922%29.mp4",
            trailerURL: nil,
            cast: ["Nanook", "Nyla", "Cunayou"],
            director: "Robert J. Flaherty",
            year: 1922,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-man-with-a-movie-camera-1929",
            title: "Man with a Movie Camera",
            posterURL: "https://image.tmdb.org/t/p/w500/wLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/wLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "A visual poem of Soviet city life from dawn to dusk. Voted the greatest documentary ever made!",
            releaseDate: "1929-01-08",
            runtime: 68,
            genre: [.documentary],
            rating: "G",
            imdbRating: 8.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ManWithAMovieCamera1929/Man%20with%20a%20Movie%20Camera%20%281929%29.mp4",
            trailerURL: nil,
            cast: [],
            director: "Dziga Vertov",
            year: 1929,
            language: "Silent",
            country: "SU",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-night-and-fog-1955",
            title: "Night and Fog (Nuit et Brouillard)",
            posterURL: "https://image.tmdb.org/t/p/w500/xLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/xLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "A devastating short documentary about the Nazi concentration camps. Alain Resnais' powerful Holocaust memorial!",
            releaseDate: "1955-10-28",
            runtime: 32,
            genre: [.documentary, .war],
            rating: "PG",
            imdbRating: 8.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/NightAndFog1955/Night%20and%20Fog%20%281955%29.mp4",
            trailerURL: nil,
            cast: [],
            director: "Alain Resnais",
            year: 1955,
            language: "French",
            country: "FR",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-plow-that-broke-the-plains-1936",
            title: "The Plow That Broke the Plains",
            posterURL: "https://image.tmdb.org/t/p/w500/yLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/yLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "The story of the Dust Bowl and the Great Plains. Pare Lorentz's landmark government documentary with Virgil Thomson score!",
            releaseDate: "1936-05-10",
            runtime: 25,
            genre: [.documentary, .drama],
            rating: "G",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/ThePlowThatBrokeThePlains1936/The%20Plow%20That%20Broke%20the%20Plains%20%281936%29.mp4",
            trailerURL: nil,
            cast: [],
            director: "Pare Lorentz",
            year: 1936,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-river-1938",
            title: "The River",
            posterURL: "https://image.tmdb.org/t/p/w500/zLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/zLJqLqLqLqLqLqLqLqLqLqLqLq2.jpg",
            overview: "The story of the Mississippi River and its role in American life. Pare Lorentz's poetic documentary masterpiece!",
            releaseDate: "1938-10-02",
            runtime: 31,
            genre: [.documentary],
            rating: "G",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheRiver1938/The%20River%20%281938%29.mp4",
            trailerURL: nil,
            cast: [],
            director: "Pare Lorentz",
            year: 1938,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎭 MORE DRAMA MASTERPIECES - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-the-outcasts-of-poker-flat-1937",
            title: "The Outcasts of Poker Flat",
            posterURL: "https://image.tmdb.org/t/p/w500/1LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/1LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A group of social outcasts are stranded in a mountain cabin during a blizzard. Bret Harte's classic Western tale!",
            releaseDate: "1937-11-14",
            runtime: 73,
            genre: [.western, .drama, .romance],
            rating: "G",
            imdbRating: 6.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheOutcastsOfPokerFlat1937/The%20Outcasts%20of%20Poker%20Flat%20%281937%29.mp4",
            trailerURL: nil,
            cast: ["Preston Foster", "Jean Muir", "Van Heflin"],
            director: "Christy Cabanne",
            year: 1937,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-of-mice-and-men-1939",
            title: "Of Mice and Men",
            posterURL: "https://image.tmdb.org/t/p/w500/2LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/2LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Two migrant workers dream of owning a farm, but fate has other plans. Steinbeck's heartbreaking story on film!",
            releaseDate: "1939-12-30",
            runtime: 106,
            genre: [.drama, .adventure],
            rating: "PG",
            imdbRating: 7.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/OfMiceAndMen1939/Of%20Mice%20and%20Men%20%281939%29.mp4",
            trailerURL: nil,
            cast: ["Burgess Meredith", "Lon Chaney Jr.", "Betty Field"],
            director: "Lewis Milestone",
            year: 1939,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-grapes-of-wrath-1940-excerpt",
            title: "The Grapes of Wrath (Excerpt)",
            posterURL: "https://image.tmdb.org/t/p/w500/3LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "The Joad family's powerful journey from Oklahoma to California. Henry Fonda and Jane Darwell in John Ford's masterpiece!",
            releaseDate: "1940-01-24",
            runtime: 15,
            genre: [.drama],
            rating: "G",
            imdbRating: 8.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGrapesOfWrath1940Excerpt/The%20Grapes%20of%20Wrath%20%281940%29%20-%20Excerpt.mp4",
            trailerURL: "https://www.youtube.com/watch?v=jA7iHVLuGV8",
            cast: ["Henry Fonda", "Jane Darwell"],
            director: "John Ford",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-southerner-1945",
            title: "The Southerner",
            posterURL: "https://image.tmdb.org/t/p/w500/4LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/4LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A tenant farmer struggles to build a life for his family on his own land. Jean Renoir's poetic American drama!",
            releaseDate: "1945-08-29",
            runtime: 92,
            genre: [.drama, .romance],
            rating: "PG",
            imdbRating: 7.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheSoutherner1945/The%20Southerner%20%281945%29.mp4",
            trailerURL: nil,
            cast: ["Zachary Scott", "Betty Field", "J. Carrol Naish"],
            director: "Jean Renoir",
            year: 1945,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-our-daily-bread-1934",
            title: "Our Daily Bread",
            posterURL: "https://image.tmdb.org/t/p/w500/5LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/5LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Unemployed city dwellers form a cooperative farm during the Depression. King Vidor's inspiring social drama!",
            releaseDate: "1934-09-20",
            runtime: 79,
            genre: [.drama, .romance],
            rating: "G",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/OurDailyBread1934/Our%20Daily%20Bread%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["Tom Keene", "Karen Morley", "John Rutherford"],
            director: "King Vidor",
            year: 1934,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-ram-rodder-1935",
            title: "The Phantom Rangler",
            posterURL: "https://image.tmdb.org/t/p/w500/6LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A cowboy battles rustlers and wins the girl in this action-packed B-western. Classic 1930s western adventure!",
            releaseDate: "1935-06-15",
            runtime: 56,
            genre: [.western, .action],
            rating: "G",
            imdbRating: 5.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheRamRodderr1935/The%20Ram%20Rodderr%20%281935%29.mp4",
            trailerURL: nil,
            cast: ["Wally Wales", "Virginia Browne Faire"],
            director: "Robert N. Bradbury",
            year: 1935,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎵 MORE MUSICALS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-second-chorus-1940",
            title: "Second Chorus",
            posterURL: "https://image.tmdb.org/t/p/w500/7LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/7LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "Two rival trumpet players compete for a spot in Artie Shaw's band and the same girl. Fred Astaire musical comedy!",
            releaseDate: "1940-12-25",
            runtime: 83,
            genre: [.musical, .comedy, .romance],
            rating: "G",
            imdbRating: 6.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/SecondChorus1940/Second%20Chorus%20%281940%29.mp4",
            trailerURL: nil,
            cast: ["Fred Astaire", "Paulette Goddard", "Artie Shaw"],
            director: "H.C. Potter",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-royal-wedding-1951-alt",
            title: "Royal Wedding",
            posterURL: "https://image.tmdb.org/t/p/w500/8LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A dance team finds romance during London's royal wedding. Features Astaire's legendary ceiling dance!",
            releaseDate: "1951-03-23",
            runtime: 93,
            genre: [.musical, .comedy, .romance],
            rating: "G",
            imdbRating: 6.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/RoyalWedding1951/Royal%20Wedding%20%281951%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=CsoYyDlYU8M",
            cast: ["Fred Astaire", "Jane Powell", "Peter Lawford"],
            director: "Stanley Donen",
            year: 1951,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-little-princess-1939",
            title: "The Little Princess",
            posterURL: "https://image.tmdb.org/t/p/w500/9LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9LJqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A wealthy girl becomes a servant when her father goes missing in war. Shirley Temple's Technicolor classic!",
            releaseDate: "1939-03-17",
            runtime: 91,
            genre: [.drama, .family, .musical],
            rating: "G",
            imdbRating: 7.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLittlePrincess1939/The%20Little%20Princess%20%281939%29.mp4",
            trailerURL: nil,
            cast: ["Shirley Temple", "Richard Greene", "Anita Louise"],
            director: "Walter Lang",
            year: 1939,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-his-girl-friday-1940-alt",
            title: "His Girl Friday (Alternate Source)",
            posterURL: "https://image.tmdb.org/t/p/w500/0LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/0LJqLqLqLqLqLqLqLqLqLqLqLq3.jpg",
            overview: "A newspaper editor tries to win back his ex-wife reporter with one last big story. Cary Grant at his fastest and funniest!",
            releaseDate: "1940-01-18",
            runtime: 92,
            genre: [.comedy, .romance, .drama],
            rating: "G",
            imdbRating: 8.0,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/HisGirlFriday1940/His%20Girl%20Friday%20%281940%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=9XJ5q1Z4gX0",
            cast: ["Cary Grant", "Rosalind Russell", "Ralph Bellamy"],
            director: "Howard Hawks",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🧙‍♂️ FANTASY & FAIRY TALES - FULL MOVIES
        // ============================================
        
    ]
}
