import Foundation

extension FreeMovie {
    // MARK: Chunk 1
    static let _smc01: [FreeMovie] = [
        FreeMovie(
            id: "ia-sita-sings-blues",
            title: "Sita Sings the Blues",
            posterURL: "https://image.tmdb.org/t/p/w500/pFxVnhJ9kQl6aPRJaIjPFGLmkR8.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/pFxVnhJ9kQl6aPRJaIjPFGLmkR8.jpg",
            overview: "An animated musical that weaves together the ancient Hindu epic Ramayana with a modern story of heartbreak. Visually stunning and critically acclaimed!",
            releaseDate: "2008-02-12",
            runtime: 82,
            genre: [.animation, .musical, .romance],
            rating: "PG",
            imdbRating: 7.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Sita_Sings_the_Blues/Sita_Sings_the_Blues_1080.mp4",
            trailerURL: "https://www.youtube.com/watch?v=1V-E8Y1EMGM",
            cast: ["Annette Hanshaw", "Aseem Chhabra", "Bhavana Nagulapally"],
            director: "Nina Paley",
            year: 2008,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-cosmos-laundromat",
            title: "Cosmos Laundromat",
            posterURL: "https://i.ytimg.com/vi/Y-rmzh0PI3c/hqdefault.jpg",
            backdropURL: "https://i.ytimg.com/vi/Y-rmzh0PI3c/maxresdefault.jpg",
            overview: "A suicidal sheep named Franck meets a mysterious being who offers him the chance to live infinite lives. Mind-bending animated adventure from Blender Foundation!",
            releaseDate: "2015-08-10",
            runtime: 12,
            genre: [.animation, .fantasy, .adventure],
            rating: "PG",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CosmosLaundromat/Cosmos_Laundromat_-_First_Cycle_-_Official_Blender_Foundation_release.mp4",
            trailerURL: "https://www.youtube.com/watch?v=Y-rmzh0PI3c",
            cast: [],
            director: "Mathieu Auvray",
            year: 2015,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-spring-blender",
            title: "Spring",
            posterURL: "https://i.ytimg.com/vi/WhWc3b3KhnY/hqdefault.jpg",
            backdropURL: "https://i.ytimg.com/vi/WhWc3b3KhnY/maxresdefault.jpg",
            overview: "A shepherd girl and her magical dog embark on a perilous journey through ancient lands. Breathtaking Blender animation with stunning visuals!",
            releaseDate: "2019-04-04",
            runtime: 8,
            genre: [.animation, .fantasy, .adventure],
            rating: "G",
            imdbRating: 7.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/spring-blender-open-movie/spring-blender-open-movie.mp4",
            trailerURL: "https://www.youtube.com/watch?v=WhWc3b3KhnY",
            cast: [],
            director: "Andy Goralczyk",
            year: 2019,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-agent-327",
            title: "Agent 327: Operation Barbershop",
            posterURL: "https://i.ytimg.com/vi/mN0zPOpADL4/hqdefault.jpg",
            backdropURL: "https://i.ytimg.com/vi/mN0zPOpADL4/maxresdefault.jpg",
            overview: "Secret agent 327 must stop a villain in a barbershop that's more than it seems. High-octane spy action with incredible 3D animation!",
            releaseDate: "2017-05-15",
            runtime: 4,
            genre: [.animation, .action, .comedy],
            rating: "PG",
            imdbRating: 7.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/agent-327-operation-barbershop/Agent%20327%20-%20Operation%20Barbershop.mp4",
            trailerURL: "https://www.youtube.com/watch?v=mN0zPOpADL4",
            cast: [],
            director: "Colin Levy",
            year: 2017,
            language: "English",
            country: "NL",
            isAvailable: true
        ),
        
        // ============================================
        // 🎬 ACTION & THRILLER FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-charade-1963",
            title: "Charade",
            posterURL: "https://image.tmdb.org/t/p/w500/5K2U4bXkClvmjxY9QMMj4yYtJKv.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8GvKG3n2hWEyKTpNfC8Gu5Y6yvV.jpg",
            overview: "Romance and suspense ensue in Paris as a woman is pursued by several men who want a fortune her murdered husband had stolen. Who can she trust?",
            releaseDate: "1963-12-05",
            runtime: 113,
            genre: [.thriller, .romance, .comedy],
            rating: "PG",
            imdbRating: 7.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Charade_201610/Charade.mp4",
            trailerURL: "https://www.youtube.com/watch?v=k1q5lkG4ZMA",
            cast: ["Cary Grant", "Audrey Hepburn", "Walter Matthau", "James Coburn"],
            director: "Stanley Donen",
            year: 1963,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-house-on-haunted-hill-1959",
            title: "House on Haunted Hill",
            posterURL: "https://image.tmdb.org/t/p/w500/oDBuPTXRw6d1TmLPuTPp7rvS8FR.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/ixXM7kO8aLx0i8rT5eiP8kFJSr3.jpg",
            overview: "A millionaire offers $10,000 to five people who agree to be locked in a large, spooky, rented house overnight with him and his wife.",
            releaseDate: "1959-02-17",
            runtime: 75,
            genre: [.horror, .mystery],
            rating: "PG",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/house_on_haunted_hill/house_on_haunted_hill_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=UfqQOVi7YCA",
            cast: ["Vincent Price", "Carol Ohmart", "Richard Long"],
            director: "William Castle",
            year: 1959,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-night-of-the-living-dead",
            title: "Night of the Living Dead",
            posterURL: "https://image.tmdb.org/t/p/w500/bQXEaYLRh1SeDsICoZ6irMIX2bZ.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3YgK9ZkZ4fU2KqgEBeS3T1jCz2m.jpg",
            overview: "A group barricades themselves in a farmhouse to survive a zombie outbreak. The film that launched the modern zombie genre!",
            releaseDate: "1968-10-01",
            runtime: 96,
            genre: [.horror, .thriller],
            rating: "R",
            imdbRating: 7.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/night_of_the_living_dead/night_of_the_living_dead_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=6G5pyFhmAqE",
            cast: ["Duane Jones", "Judith O'Dea", "Karl Hardman"],
            director: "George A. Romero",
            year: 1968,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-mclintock-1963",
            title: "McLintock!",
            posterURL: "https://image.tmdb.org/t/p/w500/lXW5P5MfYMi8xwA5hnlxzWcMJHm.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/5hF6HjG2XC8Wo9FcQhW9lVvPdqP.jpg",
            overview: "A wealthy rancher tries to keep the peace between ranchers and settlers, while his wife returns home seeking a divorce.",
            releaseDate: "1963-11-13",
            runtime: 127,
            genre: [.western, .comedy, .romance],
            rating: "G",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/McLintock1963/McLintock%21%20%281963%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=FbYQH1pAl2o",
            cast: ["John Wayne", "Maureen O'Hara", "Patrick Wayne"],
            director: "Andrew V. McLaglen",
            year: 1963,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-little-shop-of-horrors-1960",
            title: "The Little Shop of Horrors",
            posterURL: "https://image.tmdb.org/t/p/w500/aQLfVyPJNVFV3Gu5tn2Z3wVK3AC.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/oNg0yJl9LnLXGqE3YC3xkVTYxqL.jpg",
            overview: "A nerdy florist discovers a strange plant that feeds on human flesh. Features Jack Nicholson in an early role!",
            releaseDate: "1960-08-05",
            runtime: 72,
            genre: [.comedy, .horror],
            rating: "PG",
            imdbRating: 6.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLittleShopOfHorrors1960/TheLittleShopOfHorrors1960.mp4",
            trailerURL: "https://www.youtube.com/watch?v=YXO9aIMlXoQ",
            cast: ["Jonathan Haze", "Jackie Joseph", "Jack Nicholson"],
            director: "Roger Corman",
            year: 1960,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 👻 HORROR CLASSICS
        // ============================================
        
        FreeMovie(
            id: "ia-carnival-of-souls-1962",
            title: "Carnival of Souls",
            posterURL: "https://image.tmdb.org/t/p/w500/5mwfZaBgW0BM8lIGHDH3tPbGkNU.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qOvKQ2nVYfCKFQ2vN0RBWPFKHJM.jpg",
            overview: "After a traumatic car accident, a woman becomes drawn to a mysterious abandoned carnival. A haunting cult classic!",
            releaseDate: "1962-09-26",
            runtime: 78,
            genre: [.horror, .mystery],
            rating: "PG",
            imdbRating: 7.1,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/CarnivalOfSouls/Carnival%20of%20Souls.mp4",
            trailerURL: "https://www.youtube.com/watch?v=y8BPRVLYNIo",
            cast: ["Candace Hilligoss", "Frances Feist", "Sidney Berger"],
            director: "Herk Harvey",
            year: 1962,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-nosferatu-1922",
            title: "Nosferatu",
            posterURL: "https://image.tmdb.org/t/p/w500/bFjQD0HGAXRTWMHhxhvyRJ7Njj4.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6kGOa3hhB2t9Q3A1wQ6lFVH6bQv.jpg",
            overview: "The original vampire film! Count Orlok terrorizes a German town. A masterpiece of German Expressionism.",
            releaseDate: "1922-03-04",
            runtime: 94,
            genre: [.horror, .fantasy],
            rating: "PG",
            imdbRating: 7.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/nosferatu_1922/Nosferatu%20%281922%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=rcyzubFvBsA",
            cast: ["Max Schreck", "Gustav von Wangenheim"],
            director: "F.W. Murnau",
            year: 1922,
            language: "Silent",
            country: "DE",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-dementia-13-1963",
            title: "Dementia 13",
            posterURL: "https://image.tmdb.org/t/p/w500/gOd7nGG4lGX4YMrQ6Q7PGXVJ3AL.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8jKxkzMqBFAq0fCKRJiALEBMjnt.jpg",
            overview: "A scheming widow hatches a daring plan to get her hands on the family fortune. Francis Ford Coppola's directorial debut!",
            releaseDate: "1963-09-25",
            runtime: 75,
            genre: [.horror, .thriller],
            rating: "R",
            imdbRating: 5.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Dementia13/Dementia13.mp4",
            trailerURL: "https://www.youtube.com/watch?v=JQN1nFSW4nc",
            cast: ["William Campbell", "Luana Anders", "Patrick Magee"],
            director: "Francis Ford Coppola",
            year: 1963,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-the-terror-1963",
            title: "The Terror",
            posterURL: "https://image.tmdb.org/t/p/w500/7L5dU0j4yF6AffHJvTKiNJBAG5C.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9rVyZGr2kFME5AHYoJF8K7mTL7E.jpg",
            overview: "A soldier encounters a mysterious woman and discovers dark secrets in an ancient castle. Stars Boris Karloff & Jack Nicholson!",
            releaseDate: "1963-06-15",
            runtime: 81,
            genre: [.horror, .mystery],
            rating: "PG",
            imdbRating: 4.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheTerror1963/The%20Terror%20%281963%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=s6h5Zj5aXlQ",
            cast: ["Boris Karloff", "Jack Nicholson", "Sandra Knight"],
            director: "Roger Corman",
            year: 1963,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-last-man-on-earth-1964",
            title: "The Last Man on Earth",
            posterURL: "https://image.tmdb.org/t/p/w500/f4x2GQKp7tB9H4mWmFv8V1l8VfP.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9yqHj1kP3n8u2l6qG1e5k5j7dYk.jpg",
            overview: "The sole survivor of a pandemic that turned everyone into vampires fights to survive. Inspired 'I Am Legend'!",
            releaseDate: "1964-03-08",
            runtime: 86,
            genre: [.scifi, .horror],
            rating: "PG",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLastManOnEarth1964/TheLastManOnEarth1964_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=haJZ6tWc2Dk",
            cast: ["Vincent Price", "Franca Bettoia"],
            director: "Ubaldo Ragona",
            year: 1964,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-brain-that-wouldnt-die-1962",
            title: "The Brain That Wouldn't Die",
            posterURL: "https://image.tmdb.org/t/p/w500/3kJ8YHGPJkdnYqwQvQ3PZjU3hkv.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8eV1L3lQKJvVGtZVMcEHVFJv5Wd.jpg",
            overview: "A mad scientist keeps his fiancée's severed head alive while searching for a new body for her. Classic B-movie horror!",
            releaseDate: "1962-05-03",
            runtime: 82,
            genre: [.horror, .scifi],
            rating: "R",
            imdbRating: 4.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheBrainThatWouldntDie1962/The%20Brain%20That%20Wouldnt%20Die%20%281962%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=tPXWdXZ0QyM",
            cast: ["Jason Evers", "Virginia Leith"],
            director: "Joseph Green",
            year: 1962,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🎭 CLASSIC COMEDY & DRAMA
        // ============================================
        
        FreeMovie(
            id: "ia-his-girl-friday-1940",
            title: "His Girl Friday",
            posterURL: "https://image.tmdb.org/t/p/w500/9nX0aPZ3x1iG2R0V3QwVQyqE0Jd.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6k7t9Q4zXb3KtF0z5Zt4yY7Vb1T.jpg",
            overview: "A newspaper editor uses every trick to keep his ex-wife from remarrying as they chase a big story. Classic screwball comedy!",
            releaseDate: "1940-01-18",
            runtime: 92,
            genre: [.comedy, .romance],
            rating: "G",
            imdbRating: 7.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/his_girl_friday/his_girl_friday_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=K7wzGFGZ7nM",
            cast: ["Cary Grant", "Rosalind Russell", "Ralph Bellamy"],
            director: "Howard Hawks",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-a-star-is-born-1937",
            title: "A Star Is Born",
            posterURL: "https://image.tmdb.org/t/p/w500/ygMevYgqwA9VXM0mPXhBpLcULQM.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3qn0qVRzQ3xCc9m1Lz0hOZKLNWg.jpg",
            overview: "The original! A young actress rises to fame as her alcoholic husband's career declines. A timeless Hollywood story.",
            releaseDate: "1937-04-27",
            runtime: 111,
            genre: [.drama, .romance],
            rating: "G",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/AStarIsBorn1937/A%20Star%20Is%20Born%20%281937%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=c8WvH5lK_q8",
            cast: ["Janet Gaynor", "Fredric March", "Adolphe Menjou"],
            director: "William A. Wellman",
            year: 1937,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-reefer-madness-1936",
            title: "Reefer Madness",
            posterURL: "https://image.tmdb.org/t/p/w500/xHgE15xX3dNaBWqCF3g4XlkCNMq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/8pQNnVk3X6Cv5zQHqK8zQONVmQh.jpg",
            overview: "A propaganda film turned cult classic! Teens spiral into madness after trying marijuana. Unintentionally hilarious today!",
            releaseDate: "1936-01-01",
            runtime: 66,
            genre: [.drama, .crime],
            rating: "PG",
            imdbRating: 3.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/reefer_madness/reefer_madness.mp4",
            trailerURL: "https://www.youtube.com/watch?v=zhQlcMHhF3w",
            cast: ["Dorothy Short", "Kenneth Craig"],
            director: "Louis J. Gasnier",
            year: 1936,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-beat-the-devil-1953",
            title: "Beat the Devil",
            posterURL: "https://image.tmdb.org/t/p/w500/4Jb8yC3h3X7mwr2H6Sx7pS5JQZq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/6h1F1qj4k2wYv5qY3Jv3gU2mC0R.jpg",
            overview: "A group of swindlers scheme to get rich off African uranium. Humphrey Bogart in a comedy adventure!",
            releaseDate: "1953-11-05",
            runtime: 89,
            genre: [.comedy, .adventure],
            rating: "PG",
            imdbRating: 6.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/beat_the_devil/beat_the_devil_512kb.mp4",
            trailerURL: nil,
            cast: ["Humphrey Bogart", "Jennifer Jones", "Gina Lollobrigida"],
            director: "John Huston",
            year: 1953,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🔍 FILM NOIR & THRILLER
        // ============================================
        
        FreeMovie(
            id: "ia-doa-1950",
            title: "D.O.A.",
            posterURL: "https://image.tmdb.org/t/p/w500/d4wcuG3EWMNAK4lSRrS1YQ7j5wC.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/7G5Qf3wXv0F4h7mWzQu3m1jTjXU.jpg",
            overview: "A poisoned man has 24 hours to find his own killer before he dies. The ultimate noir premise!",
            releaseDate: "1950-04-21",
            runtime: 83,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/DOA_1950/DOA_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=V9dQ0C6pYt4",
            cast: ["Edmond O'Brien", "Pamela Britton"],
            director: "Rudolph Maté",
            year: 1950,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        FreeMovie(
            id: "ia-detour-1945",
            title: "Detour",
            posterURL: "https://image.tmdb.org/t/p/w500/8mF9QYz9QK4bJ3j6Rr7x9c3ZxJd.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3qF3W6g3t7i2n0jV3QfG1wXq9Uy.jpg",
            overview: "A hitchhiker's ride leads to murder and blackmail. One of the greatest B-movies ever made!",
            releaseDate: "1945-11-30",
            runtime: 68,
            genre: [.crime, .thriller],
            rating: "PG",
            imdbRating: 7.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Detour1945/Detour_512kb.mp4",
            trailerURL: "https://www.youtube.com/watch?v=8rj2sQXGQ9k",
            cast: ["Tom Neal", "Ann Savage"],
            director: "Edgar G. Ulmer",
            year: 1945,
            language: "English",
            country: "US",
            isAvailable: true
        ),
    ]
}
