import Foundation

extension FreeMovie {
    // MARK: Chunk 5
    static let _smc05: [FreeMovie] = [
        FreeMovie(
            id: "ia-the-iron-mask-1929",
            title: "The Iron Mask",
            posterURL: "https://image.tmdb.org/t/p/w500/nKJbPNZqHjFT5YN9Gkm1HrqMNWX.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/nKJbPNZqHjFT5YN9Gkm1HrqMNWX.jpg",
            overview: "D'Artagnan and the Three Musketeers protect the rightful King of France. Douglas Fairbanks' thrilling swashbuckler!",
            releaseDate: "1929-02-21",
            runtime: 97,
            genre: [.adventure, .action, .drama],
            rating: "G",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheIronMask1929/The%20Iron%20Mask%20%281929%29.mp4",
            trailerURL: nil,
            cast: ["Douglas Fairbanks", "Belle Bennett", "Marguerite De La Motte"],
            director: "Allan Dwan",
            year: 1929,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-thief-of-bagdad-1924",
            title: "The Thief of Bagdad",
            posterURL: "https://image.tmdb.org/t/p/w500/3QHTOkq9DZb3IIcFFnL8eXxjFKv.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3QHTOkq9DZb3IIcFFnL8eXxjFKv.jpg",
            overview: "A charming thief must complete impossible quests to win a princess. Douglas Fairbanks in a visual spectacle!",
            releaseDate: "1924-03-18",
            runtime: 155,
            genre: [.adventure, .fantasy, .romance],
            rating: "G",
            imdbRating: 7.6,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheThiefOfBagdad1924/The%20Thief%20of%20Bagdad%20%281924%29.mp4",
            trailerURL: nil,
            cast: ["Douglas Fairbanks", "Julanne Johnston", "Anna May Wong"],
            director: "Raoul Walsh",
            year: 1924,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-d-o-a-1988",
            title: "Dead on Arrival",
            posterURL: "https://image.tmdb.org/t/p/w500/3PQvnxG3K1S7F5R8K5B2g1lFl8r.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/3PQvnxG3K1S7F5R8K5B2g1lFl8r.jpg",
            overview: "A college professor discovers he's been poisoned and has only 24 hours to find his killer. Gripping 80s noir remake!",
            releaseDate: "1988-03-18",
            runtime: 96,
            genre: [.thriller, .mystery, .crime],
            rating: "R",
            imdbRating: 5.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/D.O.A.1988/D.O.A.%20%281988%29.mp4",
            trailerURL: nil,
            cast: ["Dennis Quaid", "Meg Ryan", "Charlotte Rampling"],
            director: "Rocky Morton",
            year: 1988,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-great-train-robbery-1903",
            title: "The Great Train Robbery",
            posterURL: "https://image.tmdb.org/t/p/w500/9lXAErVUEVL9MFyI66GIoK8N8Y5.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/9lXAErVUEVL9MFyI66GIoK8N8Y5.jpg",
            overview: "Bandits rob a train and are pursued by a posse. The film that launched cinema as a storytelling medium!",
            releaseDate: "1903-12-01",
            runtime: 12,
            genre: [.western, .action, .crime],
            rating: "G",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheGreatTrainRobbery1903/The%20Great%20Train%20Robbery%20%281903%29.mp4",
            trailerURL: nil,
            cast: ["Gilbert M. Anderson", "A.C. Abadie"],
            director: "Edwin S. Porter",
            year: 1903,
            language: "Silent",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🕵️ MYSTERY & CRIME - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-m-1931",
            title: "M",
            posterURL: "https://image.tmdb.org/t/p/w500/dBdE6b91dWjGRW3PkvMfXrjhMnH.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/dBdE6b91dWjGRW3PkvMfXrjhMnH.jpg",
            overview: "A serial child murderer is hunted by both police and criminals. Fritz Lang's groundbreaking thriller starring Peter Lorre!",
            releaseDate: "1931-05-11",
            runtime: 117,
            genre: [.crime, .thriller, .drama],
            rating: "PG",
            imdbRating: 8.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/M_1931/M%20%281931%29.mp4",
            trailerURL: "https://www.youtube.com/watch?v=nH-N1KnU_hU",
            cast: ["Peter Lorre", "Ellen Widmann", "Inge Landgut"],
            director: "Fritz Lang",
            year: 1931,
            language: "German",
            country: "DE",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-maltese-falcon-1931",
            title: "The Maltese Falcon (1931)",
            posterURL: "https://image.tmdb.org/t/p/w500/sYRf7DY3UmASTKoUPNfvRBEPaJ0.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/sYRf7DY3UmASTKoUPNfvRBEPaJ0.jpg",
            overview: "Private detective Sam Spade takes on a case that leads to a priceless statuette. The original pre-Code version!",
            releaseDate: "1931-05-28",
            runtime: 80,
            genre: [.crime, .mystery, .drama],
            rating: "PG",
            imdbRating: 6.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheMalteseFalcon1931/The%20Maltese%20Falcon%20%281931%29.mp4",
            trailerURL: nil,
            cast: ["Bebe Daniels", "Ricardo Cortez", "Dudley Digges"],
            director: "Roy Del Ruth",
            year: 1931,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-big-sleep-trailer",
            title: "The Big Sleep (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/gI7OBjWjQkwTbzlhdWRMg5ESJcg.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/gI7OBjWjQkwTbzlhdWRMg5ESJcg.jpg",
            overview: "Philip Marlowe investigates a wealthy family's dark secrets. Bogart & Bacall in peak noir!",
            releaseDate: "1946-08-23",
            runtime: 3,
            genre: [.crime, .mystery, .thriller],
            rating: "PG",
            imdbRating: 7.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheBigSleepTrailer/The%20Big%20Sleep%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=ESnHVxlPyXE",
            cast: ["Humphrey Bogart", "Lauren Bacall", "Martha Vickers"],
            director: "Howard Hawks",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-lodger-1927",
            title: "The Lodger: A Story of the London Fog",
            posterURL: "https://image.tmdb.org/t/p/w500/5N2SEXc6L6Nxn0gQJhQRUkwKMd4.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/5N2SEXc6L6Nxn0gQJhQRUkwKMd4.jpg",
            overview: "A mysterious lodger may be the serial killer terrorizing London. Hitchcock's first true thriller!",
            releaseDate: "1927-02-14",
            runtime: 91,
            genre: [.thriller, .mystery, .horror],
            rating: "PG",
            imdbRating: 7.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLodger1927/The%20Lodger%20%281927%29.mp4",
            trailerURL: nil,
            cast: ["Ivor Novello", "June Tripp", "Malcolm Keen"],
            director: "Alfred Hitchcock",
            year: 1927,
            language: "Silent",
            country: "UK",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-shock-1946",
            title: "Shock",
            posterURL: "https://image.tmdb.org/t/p/w500/lK4HpRFC2cJPQQnlhTdBYvPJKmT.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/lK4HpRFC2cJPQQnlhTdBYvPJKmT.jpg",
            overview: "A woman witnesses a murder from her hotel window and the killer turns out to be her psychiatrist. Tense noir!",
            releaseDate: "1946-02-01",
            runtime: 70,
            genre: [.thriller, .mystery, .crime],
            rating: "PG",
            imdbRating: 6.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/Shock1946/Shock%20%281946%29.mp4",
            trailerURL: nil,
            cast: ["Vincent Price", "Lynn Bari", "Frank Latimore"],
            director: "Alfred L. Werker",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-chase-1946",
            title: "The Chase",
            posterURL: "https://image.tmdb.org/t/p/w500/jF7hRYp7mJQCLp0wN8TSJfnLQX8.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/jF7hRYp7mJQCLp0wN8TSJfnLQX8.jpg",
            overview: "A WWII veteran becomes chauffeur to a dangerous gangster and falls for his wife. Dreamlike noir thriller!",
            releaseDate: "1946-11-17",
            runtime: 86,
            genre: [.thriller, .crime, .mystery],
            rating: "PG",
            imdbRating: 6.7,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheChase1946/The%20Chase%20%281946%29.mp4",
            trailerURL: nil,
            cast: ["Robert Cummings", "Michèle Morgan", "Steve Cochran"],
            director: "Arthur Ripley",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 👻 MORE HORROR - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-white-zombie-1932",
            title: "White Zombie",
            posterURL: "https://image.tmdb.org/t/p/w500/bXJY5HmKwGqL2qYqR1YmGjJYjJY.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/bXJY5HmKwGqL2qYqR1YmGjJYjJY.jpg",
            overview: "A man turns his rival's bride into a zombie slave on a Haitian plantation. Bela Lugosi's iconic horror performance!",
            releaseDate: "1932-08-04",
            runtime: 69,
            genre: [.horror, .fantasy],
            rating: "PG",
            imdbRating: 6.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/WhiteZombie1932/White%20Zombie%20%281932%29.mp4",
            trailerURL: nil,
            cast: ["Bela Lugosi", "Madge Bellamy", "John Harron"],
            director: "Victor Halperin",
            year: 1932,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-vampire-bat-1933",
            title: "The Vampire Bat",
            posterURL: "https://image.tmdb.org/t/p/w500/nF3JGm5hLZqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/nF3JGm5hLZqLqLqLqLqLqLqLqLq.jpg",
            overview: "A village is terrorized by blood-drained corpses and a mad scientist creates life. Pre-Code horror with Dwight Frye!",
            releaseDate: "1933-01-21",
            runtime: 65,
            genre: [.horror, .scifi],
            rating: "PG",
            imdbRating: 5.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheVampireBat1933/The%20Vampire%20Bat%20%281933%29.mp4",
            trailerURL: nil,
            cast: ["Lionel Atwill", "Fay Wray", "Dwight Frye"],
            director: "Frank R. Strayer",
            year: 1933,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-devil-doll-1936",
            title: "The Devil-Doll",
            posterURL: "https://image.tmdb.org/t/p/w500/pLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/pLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "An escaped convict uses miniaturized humans to seek revenge on those who framed him. Lionel Barrymore in a bizarre horror classic!",
            releaseDate: "1936-07-10",
            runtime: 79,
            genre: [.horror, .scifi, .thriller],
            rating: "PG",
            imdbRating: 6.4,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheDevilDoll1936/The%20Devil-Doll%20%281936%29.mp4",
            trailerURL: nil,
            cast: ["Lionel Barrymore", "Maureen O'Sullivan"],
            director: "Tod Browning",
            year: 1936,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-indian-tomb-1921",
            title: "The Indian Tomb",
            posterURL: "https://image.tmdb.org/t/p/w500/rLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/rLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A maharaja seeks revenge on his unfaithful wife and her lover. Epic silent adventure from Fritz Lang!",
            releaseDate: "1921-10-28",
            runtime: 101,
            genre: [.adventure, .drama, .romance],
            rating: "G",
            imdbRating: 6.9,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheIndianTomb1921/The%20Indian%20Tomb%20%281921%29.mp4",
            trailerURL: nil,
            cast: ["Debra Paget", "Paul Hubschmid"],
            director: "Fritz Lang",
            year: 1921,
            language: "Silent",
            country: "DE",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-mummy-1932-trailer",
            title: "The Mummy (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/kcxM5YhN5nPnKJf5R5VnL5L5R5J.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/kcxM5YhN5nPnKJf5R5VnL5L5R5J.jpg",
            overview: "An ancient mummy is revived and searches for his lost love. Boris Karloff in one of Universal's greatest monsters!",
            releaseDate: "1932-12-22",
            runtime: 3,
            genre: [.horror, .fantasy, .romance],
            rating: "PG",
            imdbRating: 7.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheMummy1932Trailer/The%20Mummy%20-%20Trailer.mp4",
            trailerURL: "https://www.youtube.com/watch?v=1-6YEBvPQxo",
            cast: ["Boris Karloff", "Zita Johann", "David Manners"],
            director: "Karl Freund",
            year: 1932,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-ape-1940",
            title: "The Ape",
            posterURL: "https://image.tmdb.org/t/p/w500/qLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/qLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A mad doctor uses gorilla blood to cure polio, with deadly consequences. Boris Karloff in a wild B-movie!",
            releaseDate: "1940-08-02",
            runtime: 62,
            genre: [.horror, .scifi],
            rating: "PG",
            imdbRating: 4.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheApe1940/The%20Ape%20%281940%29.mp4",
            trailerURL: nil,
            cast: ["Boris Karloff", "Maris Wrixon"],
            director: "William Nigh",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        // ============================================
        // 🤠 MORE WESTERNS - FULL MOVIES
        // ============================================
        
        FreeMovie(
            id: "ia-blue-skies-1946-trailer",
            title: "Blue Skies (Trailer)",
            posterURL: "https://image.tmdb.org/t/p/w500/tLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/tLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A nightclub performer and a dancer compete for the same woman. Bing Crosby and Fred Astaire together!",
            releaseDate: "1946-10-16",
            runtime: 4,
            genre: [.musical, .comedy, .romance],
            rating: "G",
            imdbRating: 6.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/BlueSkies1946Trailer/Blue%20Skies%20-%20Trailer.mp4",
            trailerURL: nil,
            cast: ["Bing Crosby", "Fred Astaire", "Joan Caulfield"],
            director: "Stuart Heisler",
            year: 1946,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-lone-rider-1941",
            title: "The Lone Rider",
            posterURL: "https://image.tmdb.org/t/p/w500/uLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/uLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A lone cowboy fights corrupt ranchers and outlaws in the Old West. Classic B-western action!",
            releaseDate: "1941-06-15",
            runtime: 56,
            genre: [.western, .action],
            rating: "G",
            imdbRating: 5.5,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheLoneRider1941/The%20Lone%20Rider%20%281941%29.mp4",
            trailerURL: nil,
            cast: ["George Houston", "Al St. John", "Hillary Brooke"],
            director: "Sam Newfield",
            year: 1941,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-durango-kid-1940",
            title: "Durango Kid",
            posterURL: "https://image.tmdb.org/t/p/w500/vLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/vLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A masked vigilante fights corruption in the Old West. The film that launched the Durango Kid series!",
            releaseDate: "1940-12-01",
            runtime: 55,
            genre: [.western, .action],
            rating: "G",
            imdbRating: 5.8,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/DurangoKid1940/Durango%20Kid%20%281940%29.mp4",
            trailerURL: nil,
            cast: ["Charles Starrett", "Luana Walters"],
            director: "Ray Nazarro",
            year: 1940,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-the-desert-trail-1935",
            title: "The Desert Trail",
            posterURL: "https://image.tmdb.org/t/p/w500/wLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/wLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A rodeo star and his gambler friend are framed for robbery and murder. John Wayne western action!",
            releaseDate: "1935-04-20",
            runtime: 58,
            genre: [.western, .action],
            rating: "G",
            imdbRating: 5.3,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/TheDesertTrail1935/The%20Desert%20Trail%20%281935%29.mp4",
            trailerURL: nil,
            cast: ["John Wayne", "Mary Kornman", "Paul Fix"],
            director: "Lewis D. Collins",
            year: 1935,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
        FreeMovie(
            id: "ia-randy-rides-alone-1934",
            title: "Randy Rides Alone",
            posterURL: "https://image.tmdb.org/t/p/w500/xLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            backdropURL: "https://image.tmdb.org/t/p/w1280/xLJqLqLqLqLqLqLqLqLqLqLqLq.jpg",
            overview: "A man is accused of murder and must clear his name while tracking the real killers. Early John Wayne western!",
            releaseDate: "1934-06-04",
            runtime: 53,
            genre: [.western, .action, .mystery],
            rating: "G",
            imdbRating: 5.2,
            streamingSource: .internetArchive,
            streamURL: "https://archive.org/download/RandyRidesAlone1934/Randy%20Rides%20Alone%20%281934%29.mp4",
            trailerURL: nil,
            cast: ["John Wayne", "Alma Francis", "George Hayes"],
            director: "Harry L. Fraser",
            year: 1934,
            language: "English",
            country: "US",
            isAvailable: true
        ),
        
    ]
}
