'use client';

// TranscriptPanel — YouTube-parity transcript engagement panel.
//   • Loads a WebVTT caption track from the video's subtitles
//   • Parses cues into timestamped lines
//   • Clicking a line seeks the player (mychannel:player-seek)
//   • Highlights + auto-scrolls the active line (mychannel:player-time)
//   • Language selector when multiple tracks exist

import { useEffect, useMemo, useRef, useState } from 'react';
import { X, ChevronDown } from 'lucide-react';
import type { SubtitleTrack } from '@/types';

interface TranscriptPanelProps {
  subtitles: SubtitleTrack[];
  onClose: () => void;
}

interface Cue {
  start: number;
  end: number;
  text: string;
}

function parseTimestamp(ts: string): number {
  // HH:MM:SS.mmm or MM:SS.mmm
  const clean = ts.trim().replace(',', '.');
  const parts = clean.split(':').map(parseFloat);
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  return parseFloat(clean) || 0;
}

function parseVTT(text: string): Cue[] {
  const cues: Cue[] = [];
  const blocks = text.replace(/\r/g, '').split('\n\n');
  for (const block of blocks) {
    const lines = block.split('\n').filter(Boolean);
    const arrowLine = lines.find((l) => l.includes('-->'));
    if (!arrowLine) continue;
    const [startRaw, endRaw] = arrowLine.split('-->');
    const start = parseTimestamp(startRaw);
    const end = parseTimestamp((endRaw ?? '').split(' ')[1] ? endRaw.trim().split(' ')[0] : endRaw);
    const textLines = lines.slice(lines.indexOf(arrowLine) + 1);
    const cueText = textLines.join(' ').replace(/<[^>]+>/g, '').trim();
    if (cueText) cues.push({ start, end: Number.isNaN(end) ? start + 4 : end, text: cueText });
  }
  return cues;
}

function fmt(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = Math.floor(secs % 60);
  const h = Math.floor(m / 60);
  if (h > 0) return `${h}:${String(m % 60).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return `${m}:${String(s).padStart(2, '0')}`;
}

export default function TranscriptPanel({ subtitles, onClose }: TranscriptPanelProps) {
  // Prefer a manual English track, else the first track.
  const ordered = useMemo(() => {
    return [...subtitles].sort((a, b) => {
      const aEn = a.languageCode?.toLowerCase().startsWith('en') ? 1 : 0;
      const bEn = b.languageCode?.toLowerCase().startsWith('en') ? 1 : 0;
      if (aEn !== bEn) return bEn - aEn;
      return Number(a.isAutoGenerated) - Number(b.isAutoGenerated);
    });
  }, [subtitles]);

  const [trackId, setTrackId] = useState(ordered[0]?.id ?? '');
  const [cues, setCues] = useState<Cue[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeIdx, setActiveIdx] = useState(-1);
  const [langMenuOpen, setLangMenuOpen] = useState(false);
  const listRef = useRef<HTMLDivElement>(null);

  const activeTrack = ordered.find((t) => t.id === trackId) ?? ordered[0];

  // Load + parse the selected track
  useEffect(() => {
    if (!activeTrack?.url) { setCues([]); setLoading(false); return; }
    let cancelled = false;
    setLoading(true);
    fetch(activeTrack.url)
      .then((r) => r.text())
      .then((text) => { if (!cancelled) setCues(parseVTT(text)); })
      .catch(() => { if (!cancelled) setCues([]); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [activeTrack?.url]);

  // Highlight the active line from the player's time pulse
  useEffect(() => {
    const onTime = (e: Event) => {
      const t = (e as CustomEvent<{ time: number }>).detail?.time ?? 0;
      setActiveIdx((prev) => {
        const next = cues.findIndex((c) => t >= c.start && t < c.end);
        return next === prev ? prev : next;
      });
    };
    window.addEventListener('mychannel:player-time', onTime as EventListener);
    return () => window.removeEventListener('mychannel:player-time', onTime as EventListener);
  }, [cues]);

  // Close on Escape
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [onClose]);

  // Auto-scroll active line into view
  useEffect(() => {
    if (activeIdx < 0 || !listRef.current) return;
    const el = listRef.current.querySelector(`[data-cue="${activeIdx}"]`);
    el?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
  }, [activeIdx]);

  const seek = (t: number) => {
    window.dispatchEvent(new CustomEvent('mychannel:player-seek', { detail: { time: t } }));
  };

  return (
    <div className="bg-[rgb(var(--color-surface))] rounded-xl mb-6 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-[rgb(var(--color-border))]">
        <h3 className="text-[15px] font-semibold text-[rgb(var(--color-text-primary))]">Transcript</h3>
        <div className="flex items-center gap-2">
          {ordered.length > 1 && (
            <div className="relative">
              <button
                onClick={() => setLangMenuOpen((v) => !v)}
                className="flex items-center gap-1 px-2.5 py-1 text-[12px] font-medium text-[rgb(var(--color-text-primary))] bg-[rgb(var(--color-background))] rounded-full hover:bg-[rgb(var(--color-surface-hover))]"
              >
                {activeTrack?.languageName ?? 'Language'}
                <ChevronDown size={13} />
              </button>
              {langMenuOpen && (
                <div className="absolute right-0 top-9 w-44 bg-[rgb(var(--color-background))] border border-[rgb(var(--color-border))] rounded-xl shadow-xl py-1.5 z-50">
                  {ordered.map((t) => (
                    <button
                      key={t.id}
                      onClick={() => { setTrackId(t.id); setLangMenuOpen(false); }}
                      className={`w-full text-left px-3 py-2 text-[13px] hover:bg-[rgb(var(--color-surface-hover))] ${t.id === trackId ? 'text-[rgb(var(--color-primary))] font-medium' : 'text-[rgb(var(--color-text-primary))]'}`}
                    >
                      {t.languageName}{t.isAutoGenerated ? ' (auto)' : ''}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}
          <button onClick={onClose} aria-label="Close transcript" className="p-1.5 hover:bg-[rgb(var(--color-surface-hover))] rounded-full">
            <X size={16} className="text-[rgb(var(--color-text-secondary))]" />
          </button>
        </div>
      </div>

      {/* Body */}
      <div ref={listRef} className="max-h-[420px] overflow-y-auto px-2 py-2">
        {loading ? (
          <p className="text-[13px] text-[rgb(var(--color-text-secondary))] text-center py-8">Loading transcript…</p>
        ) : cues.length === 0 ? (
          <p className="text-[13px] text-[rgb(var(--color-text-secondary))] text-center py-8">Transcript not available for this video.</p>
        ) : (
          cues.map((c, i) => (
            <button
              key={i}
              data-cue={i}
              onClick={() => seek(c.start)}
              className={`w-full flex gap-3 px-2 py-1.5 rounded-lg text-left transition-colors ${
                i === activeIdx ? 'bg-[rgb(var(--color-surface-hover))]' : 'hover:bg-[rgb(var(--color-surface-hover))]'
              }`}
            >
              <span className="text-[12px] font-medium text-[rgb(var(--color-primary))] tabular-nums pt-0.5 w-12 flex-shrink-0">
                {fmt(c.start)}
              </span>
              <span className="text-[13.5px] text-[rgb(var(--color-text-primary))] leading-snug">{c.text}</span>
            </button>
          ))
        )}
      </div>
    </div>
  );
}
