'use client';

// Captions / Subtitles Editor — YouTube Studio parity
// Supports adding captions tracks by language, uploading SRT/VTT files,
// and triggering auto-generated captions via Whisper ASR

import { useState, useEffect, useRef } from 'react';
import {
  ChevronLeft, Plus, Trash2, Upload, Loader2, Save,
  Subtitles, Globe, CheckCircle, AlertCircle, Zap,
} from 'lucide-react';
import Link from 'next/link';
import {
  collection, getDocs, doc, setDoc, deleteDoc, getDoc, serverTimestamp,
} from 'firebase/firestore';
import { ref, uploadString, getDownloadURL } from 'firebase/storage';
import { db, auth, storage } from '@/lib/firebase/config';

interface CaptionTrack {
  languageCode: string;
  languageName: string;
  url: string;
  isAutoGenerated: boolean;
  updatedAt?: Date;
}

const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'zh', name: 'Chinese (Simplified)' },
  { code: 'zh-TW', name: 'Chinese (Traditional)' },
  { code: 'ar', name: 'Arabic' },
  { code: 'hi', name: 'Hindi' },
  { code: 'it', name: 'Italian' },
  { code: 'ru', name: 'Russian' },
];

function parseSRT(srt: string): string {
  // Convert SRT to WebVTT format for browser playback
  let vtt = 'WEBVTT\n\n';
  const blocks = srt.trim().split(/\n\n+/);
  for (const block of blocks) {
    const lines = block.split('\n');
    if (lines.length < 3) continue;
    const timeLineIndex = lines.findIndex((l) => l.includes('-->'));
    if (timeLineIndex === -1) continue;
    const timeLine = lines[timeLineIndex].replace(/,/g, '.');
    const text = lines.slice(timeLineIndex + 1).join('\n');
    vtt += `${timeLine}\n${text}\n\n`;
  }
  return vtt;
}

export default function CaptionsEditorClient({ videoId }: { videoId: string }) {
  const [tracks, setTracks] = useState<CaptionTrack[]>([]);
  const [loading, setLoading] = useState(true);
  const [videoTitle, setVideoTitle] = useState('');
  const [videoURL, setVideoURL] = useState('');
  const [addingLang, setAddingLang] = useState('');
  const [uploading, setUploading] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [requestingAI, setRequestingAI] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const fileRefs = useRef<Record<string, HTMLInputElement | null>>({});

  useEffect(() => {
    if (!videoId || videoId === '_fallback') { setLoading(false); return; }

    const load = async () => {
      try {
        const videoSnap = await getDoc(doc(db, 'videos', videoId));
        if (videoSnap.exists()) {
          const d = videoSnap.data();
          setVideoTitle(d.title ?? 'Untitled');
          setVideoURL(d.videoURL ?? '');
        }

        const colSnap = await getDocs(collection(db, 'videos', videoId, 'captions'));
        const loaded: CaptionTrack[] = colSnap.docs.map((d) => ({
          languageCode: d.id,
          languageName: d.data().languageName ?? d.id,
          url: d.data().url ?? '',
          isAutoGenerated: d.data().isAutoGenerated ?? false,
          updatedAt: d.data().updatedAt?.toDate?.(),
        }));
        setTracks(loaded);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [videoId]);

  const handleFileUpload = async (lang: string, file: File) => {
    const uid = auth?.currentUser?.uid;
    if (!uid) { setError('Not signed in'); return; }

    setUploading(lang);
    setError('');

    try {
      let content = await file.text();
      const isSRT = file.name.endsWith('.srt');
      if (isSRT) content = parseSRT(content);

      // Upload VTT to Firebase Storage
      const storagePath = `captions/${videoId}/${lang}.vtt`;
      const storageRef = ref(storage, storagePath);
      await uploadString(storageRef, content, 'raw', { contentType: 'text/vtt' });
      const url = await getDownloadURL(storageRef);

      const langName = LANGUAGES.find((l) => l.code === lang)?.name ?? lang;

      await setDoc(doc(db, 'videos', videoId, 'captions', lang), {
        languageName: langName,
        url,
        isAutoGenerated: false,
        videoId,
        createdBy: uid,
        updatedAt: serverTimestamp(),
      });

      setTracks((prev) => {
        const existing = prev.find((t) => t.languageCode === lang);
        if (existing) {
          return prev.map((t) => t.languageCode === lang ? { ...t, url, isAutoGenerated: false } : t);
        }
        return [...prev, { languageCode: lang, languageName: langName, url, isAutoGenerated: false }];
      });

      setSuccess(`Captions uploaded for ${langName}`);
      setTimeout(() => setSuccess(''), 3000);
    } catch (e) {
      console.error(e);
      setError('Upload failed. Please try again.');
    } finally {
      setUploading(null);
    }
  };

  const handleDelete = async (lang: string) => {
    if (!confirm('Remove this caption track?')) return;
    setDeleting(lang);
    try {
      await deleteDoc(doc(db, 'videos', videoId, 'captions', lang));
      setTracks((prev) => prev.filter((t) => t.languageCode !== lang));
    } catch (e) {
      console.error(e);
      setError('Failed to delete. Please try again.');
    } finally {
      setDeleting(null);
    }
  };

  const requestAutoCaption = async (lang: string = 'en') => {
    const uid = auth?.currentUser?.uid;
    if (!uid) { setError('Not signed in'); return; }
    if (!videoURL) { setError('Video URL not available for transcription'); return; }

    setRequestingAI(true);
    setError('');

    try {
      // Write a pending job to Firestore — the Whisper ASR service picks it up
      await setDoc(doc(db, 'videos', videoId, 'captions', `${lang}_pending`), {
        languageName: LANGUAGES.find((l) => l.code === lang)?.name ?? lang,
        url: '',
        isAutoGenerated: true,
        status: 'pending',
        videoId,
        videoURL,
        targetLanguage: lang,
        requestedBy: uid,
        updatedAt: serverTimestamp(),
      });

      setSuccess('Auto-caption generation queued. This may take a few minutes.');
      setTimeout(() => setSuccess(''), 5000);
    } catch (e) {
      console.error(e);
      setError('Failed to queue auto-captions.');
    } finally {
      setRequestingAI(false);
    }
  };

  const addLanguage = () => {
    if (!addingLang || tracks.find((t) => t.languageCode === addingLang)) return;
    fileRefs.current[addingLang]?.click();
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[rgb(var(--color-background))] flex items-center justify-center">
        <Loader2 size={28} className="animate-spin text-[rgb(var(--color-text-tertiary))]" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[rgb(var(--color-background))]">
      <div className="max-w-[640px] mx-auto">
        {/* Header */}
        <header className="sticky top-0 z-50 bg-[rgb(var(--color-background))]/95 backdrop-blur border-b border-[rgb(var(--color-border))] px-4 py-3">
          <div className="flex items-center gap-3">
            <Link href={`/studio/videos/${videoId}/edit`} className="p-2 hover:bg-[rgb(var(--color-surface-hover))] rounded-full">
              <ChevronLeft size={20} className="text-[rgb(var(--color-text-primary))]" />
            </Link>
            <Subtitles size={20} className="text-blue-500" />
            <div className="flex-1 min-w-0">
              <h1 className="text-[17px] font-bold text-[rgb(var(--color-text-primary))] leading-none">Subtitles</h1>
              <p className="text-[11px] text-[rgb(var(--color-text-secondary))] truncate">{videoTitle}</p>
            </div>
          </div>
        </header>

        <main className="px-4 py-5 pb-24 space-y-4">
          {error && (
            <div className="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500 rounded-xl text-[13px] text-red-500">
              <AlertCircle size={15} /> {error}
            </div>
          )}
          {success && (
            <div className="flex items-center gap-2 p-3 bg-green-500/10 border border-green-500 rounded-xl text-[13px] text-green-500">
              <CheckCircle size={15} /> {success}
            </div>
          )}

          {/* Auto-captions card */}
          <div className="bg-[rgb(var(--color-surface))] rounded-xl p-4 border border-[rgb(var(--color-border))]">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h3 className="text-[14px] font-semibold text-[rgb(var(--color-text-primary))] mb-1 flex items-center gap-2">
                  <Zap size={15} className="text-purple-500" />
                  Auto-generate captions
                </h3>
                <p className="text-[12px] text-[rgb(var(--color-text-secondary))]">
                  Uses Whisper AI to transcribe your video automatically. Supports 90+ languages.
                </p>
              </div>
              <button
                onClick={() => requestAutoCaption('en')}
                disabled={requestingAI}
                className="flex items-center gap-1.5 px-3 py-2 bg-purple-600 text-white text-[12px] font-semibold rounded-full hover:opacity-90 disabled:opacity-50 whitespace-nowrap flex-shrink-0"
              >
                {requestingAI ? <Loader2 size={12} className="animate-spin" /> : <Zap size={12} />}
                Generate
              </button>
            </div>
          </div>

          {/* Existing tracks */}
          <div>
            <h3 className="text-[13px] font-semibold text-[rgb(var(--color-text-primary))] mb-2">
              Uploaded tracks ({tracks.length})
            </h3>

            {tracks.length === 0 ? (
              <div className="text-center py-8 text-[13px] text-[rgb(var(--color-text-secondary))]">
                No caption tracks yet. Upload SRT or VTT files below.
              </div>
            ) : (
              <div className="space-y-2">
                {tracks.map((track) => (
                  <div
                    key={track.languageCode}
                    className="flex items-center gap-3 p-3 bg-[rgb(var(--color-surface))] rounded-xl border border-[rgb(var(--color-border))]"
                  >
                    <Globe size={16} className="text-blue-500 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <p className="text-[13px] font-medium text-[rgb(var(--color-text-primary))]">
                        {track.languageName}
                      </p>
                      <p className="text-[11px] text-[rgb(var(--color-text-tertiary))]">
                        {track.isAutoGenerated ? 'Auto-generated' : 'Uploaded'}
                        {track.updatedAt ? ` · ${track.updatedAt.toLocaleDateString()}` : ''}
                      </p>
                    </div>
                    {track.url ? (
                      <CheckCircle size={15} className="text-green-500 flex-shrink-0" />
                    ) : (
                      <Loader2 size={15} className="animate-spin text-[rgb(var(--color-text-tertiary))] flex-shrink-0" />
                    )}
                    {/* Re-upload */}
                    <button
                      onClick={() => fileRefs.current[track.languageCode]?.click()}
                      disabled={uploading === track.languageCode}
                      className="p-1.5 hover:bg-[rgb(var(--color-surface-hover))] rounded-full text-[rgb(var(--color-text-secondary))]"
                      title="Replace file"
                    >
                      {uploading === track.languageCode
                        ? <Loader2 size={14} className="animate-spin" />
                        : <Upload size={14} />
                      }
                    </button>
                    <button
                      onClick={() => handleDelete(track.languageCode)}
                      disabled={deleting === track.languageCode}
                      className="p-1.5 hover:bg-red-50 dark:hover:bg-red-900/10 rounded-full text-[rgb(var(--color-text-tertiary))] hover:text-red-500"
                      title="Delete track"
                    >
                      {deleting === track.languageCode
                        ? <Loader2 size={14} className="animate-spin" />
                        : <Trash2 size={14} />
                      }
                    </button>
                    <input
                      ref={(el) => { fileRefs.current[track.languageCode] = el; }}
                      type="file"
                      accept=".srt,.vtt"
                      className="hidden"
                      onChange={(e) => {
                        const f = e.target.files?.[0];
                        if (f) handleFileUpload(track.languageCode, f);
                        e.target.value = '';
                      }}
                    />
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Add new language */}
          <div className="bg-[rgb(var(--color-surface))] rounded-xl p-4 border border-[rgb(var(--color-border))]">
            <h3 className="text-[13px] font-semibold text-[rgb(var(--color-text-primary))] mb-3">Add caption track</h3>
            <div className="flex gap-2">
              <select
                value={addingLang}
                onChange={(e) => setAddingLang(e.target.value)}
                className="flex-1 px-3 py-2 bg-[rgb(var(--color-surface-hover))] border border-[rgb(var(--color-border))] rounded-xl text-[13px] text-[rgb(var(--color-text-primary))] outline-none focus:border-[rgb(var(--color-primary))]"
              >
                <option value="">Select language…</option>
                {LANGUAGES.filter((l) => !tracks.find((t) => t.languageCode === l.code)).map((l) => (
                  <option key={l.code} value={l.code}>{l.name}</option>
                ))}
              </select>
              <button
                onClick={addLanguage}
                disabled={!addingLang}
                className="flex items-center gap-1.5 px-4 py-2 bg-[rgb(var(--color-primary))] text-white text-[13px] font-semibold rounded-xl hover:opacity-90 disabled:opacity-50"
              >
                <Upload size={14} /> Upload SRT/VTT
              </button>
            </div>
            <p className="text-[11px] text-[rgb(var(--color-text-tertiary))] mt-2">
              Accepts .srt (SubRip) and .vtt (WebVTT) files
            </p>
            {/* Hidden file input for new language */}
            {addingLang && (
              <input
                ref={(el) => { fileRefs.current[addingLang] = el; }}
                type="file"
                accept=".srt,.vtt"
                className="hidden"
                onChange={(e) => {
                  const f = e.target.files?.[0];
                  if (f) handleFileUpload(addingLang, f);
                  e.target.value = '';
                  setAddingLang('');
                }}
              />
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
