// MyChannel Web Platform - Core TypeScript Types

export interface Video {
  id: string;
  title: string;
  description: string;
  videoURL: string;
  thumbnailURL: string;
  duration: number; // seconds
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  commentCount: number;
  shareCount: number;
  createdAt: Date;
  updatedAt: Date;
  creatorId: string;
  creator: User;
  category: VideoCategory;
  tags: string[];
  isPublic: boolean;
  visibility?: 'public' | 'unlisted' | 'private' | 'scheduled';
  processingStatus?: 'uploaded' | 'queued' | 'processing' | 'ready' | 'transcode_failed';
  ageRestricted: boolean;
  madeForKids: boolean;
  commentsEnabled: boolean;
  likesEnabled: boolean;
  downloadsEnabled: boolean;
  qualityVariants?: VideoQualityVariant[];
  chapters?: VideoChapter[];
  subtitles?: SubtitleTrack[];
  contentSource?: ContentSource;
  externalID?: string;
}

export interface User {
  id: string;
  username: string;
  displayName: string;
  email: string;
  profileImageURL: string;
  bannerImageURL?: string;
  bio?: string;
  subscriberCount: number;
  videoCount: number;
  createdAt: Date;
  isVerified: boolean;
  isAdmin: boolean;
  socialLinks?: SocialLinks;
}

export interface VideoCategory {
  id: string;
  name: string;
  slug: string;
}

export interface VideoQualityVariant {
  quality: VideoQuality;
  url: string;
  fileSize: number;
  bitrate: number;
  codec: string;
}

export type VideoQuality = '240p' | '360p' | '480p' | '720p' | '1080p' | '1440p' | '4K';

export interface VideoChapter {
  id: string;
  title: string;
  startTime: number; // seconds
}

export interface SubtitleTrack {
  id: string;
  languageCode: string;
  languageName: string;
  url: string;
  isAutoGenerated: boolean;
}

export type ContentSource = 'userUploaded' | 'tmdb' | 'youtube' | 'archive';

export interface SocialLinks {
  twitter?: string;
  instagram?: string;
  tiktok?: string;
  website?: string;
}

export interface Comment {
  id: string;
  videoId: string;
  userId: string;
  user: User;
  text: string;
  createdAt: Date;
  likeCount: number;
  replyCount: number;
  parentCommentId?: string;
  isPinned: boolean;
}

export interface Flick {
  id: string;
  title: string;
  videoURL: string;
  thumbnailURL: string;
  duration: number; // max 60 seconds
  viewCount: number;
  likeCount: number;
  commentCount: number;
  shareCount: number;
  createdAt: Date;
  creatorId: string;
  creator: User;
  caption?: string;
  hashtags: string[];
  musicTrack?: MusicTrack;
}

export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  url: string;
}

export interface LiveStream {
  id: string;
  title: string;
  description: string;
  streamURL: string; // HLS URL
  thumbnailURL: string;
  creatorId: string;
  creator: User;
  viewerCount: number;
  isLive: boolean;
  startedAt: Date;
  category: string;
  tags: string[];
}

export interface VersusMatch {
  id: string;
  challengerId: string;
  challenger: User;
  opponentId: string;
  opponent: User;
  wagerAmount: number; // Dollars (legacy). Prefer wagerAmountCents for money math.
  wagerAmountCents?: number; // Canonical integer cents
  category: VersusMatchCategory;
  division: ChampionshipDivision;
  status: MatchStatus;
  createdAt: Date;
  acceptedAt?: Date;
  completedAt?: Date;
  winnerId?: string;
  escrowStatus: EscrowStatus;
  challengerVideoId?: string;
  opponentVideoId?: string;
}

export type VersusMatchCategory = 
  | 'gaming'
  | 'views'
  | 'likes'
  | 'comments'
  | 'donations'
  | 'creative'
  | 'cooking'
  | 'music'
  | 'dance'
  | 'sports';

export type ChampionshipDivision = 
  | 'bronze' // $1-100
  | 'silver' // $101-500
  | 'gold' // $501-1,000
  | 'platinum' // $1,001-5,000
  | 'diamond' // $5,001-10,000
  | 'legend'; // $10,001+

export type MatchStatus = 'pending' | 'active' | 'completed' | 'cancelled';

export type EscrowStatus = 'holding' | 'released' | 'refunded';

export interface VSMatchWallet {
  userId: string;
  availableBalance: number; // in cents
  pendingBalance: number; // in cents
  totalDeposits: number;
  totalWithdrawals: number;
  totalWinnings: number;
  totalLosses: number;
  transactions: VSMatchTransaction[];
}

export interface VSMatchTransaction {
  id: string;
  userId: string;
  type: VSMatchTransactionType;
  amount: number; // in cents
  status: VSMatchTransactionStatus;
  createdAt: Date;
  description: string;
  matchId?: string;
}

export type VSMatchTransactionType = 
  | 'deposit'
  | 'withdrawal'
  | 'wager'
  | 'win'
  | 'refund'
  | 'fee';

export type VSMatchTransactionStatus = 
  | 'pending'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface Playlist {
  id: string;
  title: string;
  description?: string;
  creatorId: string;
  creator: User;
  videoIds: string[];
  thumbnailURL?: string;
  isPublic: boolean;
  viewCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  data?: Record<string, any>;
  read: boolean;
  createdAt: Date;
}

export type NotificationType = 
  | 'video_upload'
  | 'comment_reply'
  | 'video_like'
  | 'new_subscriber'
  | 'match_invitation'
  | 'match_accepted'
  | 'match_completed'
  | 'live_stream_start';

export interface AGIAgent {
  id: string;
  name: string;
  description: string;
  category: AGIAgentCategory;
  priority: 'high' | 'medium' | 'low';
  status: AGIAgentStatus;
  isActive: boolean;
  metrics: AGIAgentMetrics;
  config: AGIAgentConfig;
}

export type AGIAgentCategory = 
  | 'money_maker'
  | 'growth'
  | 'gaming'
  | 'safety'
  | 'analytics'
  | 'scale';

export type AGIAgentStatus = 'running' | 'paused' | 'stopped' | 'error';

export interface AGIAgentMetrics {
  startTime?: Date;
  lastSuccessTime?: Date;
  lastErrorTime?: Date;
  totalRuns: number;
  successCount: number;
  errorCount: number;
  revenue: number;
  impressions: number;
  avgResponseTime: number;
  lastError?: string;
}

export interface AGIAgentConfig {
  id: string;
  runInterval: number; // seconds
  requiresNetwork: boolean;
  requiresAuth: boolean;
  modelName?: string;
  endpoint?: string;
}

export interface StreamerAward {
  id: string;
  name: string;
  description: string;
  category: StreamerAwardCategory;
  tier: AwardTier;
  points: number;
  icon: string;
  requirements: AwardRequirements;
}

export type StreamerAwardCategory = 
  | 'hours_streamed'
  | 'avg_viewers'
  | 'peak_viewers'
  | 'subscriber_growth'
  | 'engagement'
  | 'content_quality';

export type AwardTier = 
  | 'legendary'
  | 'master'
  | 'diamond'
  | 'platinum'
  | 'gold'
  | 'silver';

export interface AwardRequirements {
  minHours?: number;
  minViewers?: number;
  minSubscribers?: number;
  minEngagement?: number;
}

export interface SearchFilters {
  query?: string;
  category?: string;
  uploadDate?: 'today' | 'week' | 'month' | 'year';
  duration?: 'short' | 'medium' | 'long';
  quality?: VideoQuality;
  sortBy?: 'relevance' | 'date' | 'views' | 'rating';
}

export interface AnalyticsSummary {
  views: number;
  watchTime: number; // seconds
  revenue: number; // cents
  subscribers: number;
  likes: number;
  comments: number;
  shares: number;
  avgWatchPercentage: number;
}

