import Foundation
import AVFoundation
import UIKit

/// Phase 60: Accessibility VoiceOver Audio Descriptions
/// Uses AVSpeechSynthesizer to narrate visual scenes during silent periods of a video.
@MainActor
final class AudioDescriptionService: ObservableObject {
    static let shared = AudioDescriptionService()
    
    private let synthesizer = AVSpeechSynthesizer()
    
    // In a real FAANG app, this would be generated by a Vision language model (VLM)
    // and synced via VTT subtitle tracks.
    private var mockedDescriptions: [Double: String] = [
        5.0: "The host walks onto the stage and waves to the audience.",
        25.0: "A graph appears showing a sharp upward trend in revenue.",
        45.0: "The camera zooms in on the product, a sleek black smartphone."
    ]
    
    private var lastSpokenTime: Double = -1
    
    private init() {
        // Ensure audio session is mixed so it doesn't interrupt the video
        do {
            try AVAudioSession.sharedInstance().setCategory(.playback, options: [.mixWithOthers])
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            print("⚠️ [AudioDescription] Failed to set audio session category: \(error)")
        }
    }
    
    /// Called continuously during playback by the VideoPlayerManager time observer
    func tick(currentTime: Double) {
        guard UIAccessibility.isVoiceOverRunning else { return } // Only run if VoiceOver is active
        
        let roundedTime = (currentTime * 2).rounded() / 2.0 // Check every half second
        
        if roundedTime != lastSpokenTime, let description = mockedDescriptions[roundedTime] {
            lastSpokenTime = roundedTime
            speak(text: description)
        }
    }
    
    private func speak(text: String) {
        // Stop current speech if any
        if synthesizer.isSpeaking {
            synthesizer.stopSpeaking(at: .word)
        }
        
        let utterance = AVSpeechUtterance(string: text)
        utterance.voice = AVSpeechSynthesisVoice(language: "en-US")
        utterance.rate = AVSpeechUtteranceDefaultSpeechRate
        
        // Duck the background video audio slightly while speaking
        let audioSession = AVAudioSession.sharedInstance()
        try? audioSession.setCategory(.playback, options: [.duckOthers])
        
        synthesizer.speak(utterance)
        
        print("🗣️ [AudioDescription] Narrating: \(text)")
    }
}
