//
//  AutoCaptionsService.swift
//  MyChannel
//
//  Phase 10: Auto-captions via Cloud Run + translation to 40+ languages.
//  Wires super-ai-team for transcription and translation-ai-v2 for translation.
//

import Foundation

// MARK: - Models

struct AutoCaptionTrack: Identifiable, Codable, Hashable {
    let id: String
    let language: String         // ISO 639-1 e.g. "en"
    let languageName: String     // "English"
    let segments: [CaptionSegment]
    let isAutoGenerated: Bool

    init(id: String = UUID().uuidString, language: String, languageName: String,
         segments: [CaptionSegment], isAutoGenerated: Bool = true) {
        self.id = id; self.language = language; self.languageName = languageName
        self.segments = segments; self.isAutoGenerated = isAutoGenerated
    }

    var srtString: String {
        segments.enumerated().map { idx, seg in
            "\(idx + 1)\n\(seg.srtStart) --> \(seg.srtEnd)\n\(seg.text)\n"
        }.joined(separator: "\n")
    }
}

struct CaptionSegment: Codable, Identifiable, Hashable {
    let id: String
    let start: Double
    let end: Double
    let text: String

    init(id: String = UUID().uuidString, start: Double, end: Double, text: String) {
        self.id = id; self.start = start; self.end = end; self.text = text
    }

    var srtStart: String { Self.formatSRT(start) }
    var srtEnd: String { Self.formatSRT(end) }

    private static func formatSRT(_ t: Double) -> String {
        let h = Int(t) / 3600
        let m = (Int(t) % 3600) / 60
        let s = Int(t) % 60
        let ms = Int((t - Double(Int(t))) * 1000)
        return String(format: "%02d:%02d:%02d,%03d", h, m, s, ms)
    }
}

// MARK: - Service

@MainActor
final class AutoCaptionsService: ObservableObject {
    static let shared = AutoCaptionsService()
    private init() {}

    @Published var isTranscribing: Bool = false
    @Published var isTranslating: Bool = false
    @Published var lastError: String?

    static let supportedLanguages: [(code: String, name: String)] = [
        ("en", "English"), ("es", "Spanish"), ("fr", "French"), ("de", "German"),
        ("pt", "Portuguese"), ("it", "Italian"), ("ja", "Japanese"), ("ko", "Korean"),
        ("zh", "Chinese"), ("ar", "Arabic"), ("hi", "Hindi"), ("ru", "Russian"),
        ("tr", "Turkish"), ("nl", "Dutch"), ("pl", "Polish"), ("sv", "Swedish"),
        ("da", "Danish"), ("no", "Norwegian"), ("fi", "Finnish"), ("el", "Greek"),
        ("cs", "Czech"), ("ro", "Romanian"), ("hu", "Hungarian"), ("th", "Thai"),
        ("vi", "Vietnamese"), ("id", "Indonesian"), ("ms", "Malay"), ("tl", "Filipino"),
        ("uk", "Ukrainian"), ("bg", "Bulgarian"), ("hr", "Croatian"), ("sk", "Slovak"),
        ("sl", "Slovenian"), ("lt", "Lithuanian"), ("lv", "Latvian"), ("et", "Estonian"),
        ("he", "Hebrew"), ("fa", "Persian"), ("sw", "Swahili"), ("bn", "Bengali"),
    ]

    // MARK: - Transcribe (Whisper via Cloud Run)

    func transcribe(videoId: String, videoURL: String) async throws -> AutoCaptionTrack {
        isTranscribing = true
        lastError = nil
        defer { isTranscribing = false }

        struct Request: Encodable {
            let task: String
            let videoId: String
            let videoURL: String
            let language: String
        }
        struct RawSeg: Decodable {
            let start: Double?; let end: Double?; let text: String?
        }
        struct Response: Decodable {
            let language: String?
            let segments: [RawSeg]?
        }

        let req = Request(task: "transcribe", videoId: videoId, videoURL: videoURL, language: "auto")

        do {
            let raw: Response = try await CloudRunAgentRouter.post(
                .superAITeam, path: "/predict", body: req, timeout: 120
            )
            let segs = (raw.segments ?? []).compactMap { s -> CaptionSegment? in
                guard let start = s.start, let end = s.end,
                      let text = s.text?.trimmingCharacters(in: .whitespacesAndNewlines),
                      !text.isEmpty else { return nil }
                return CaptionSegment(start: start, end: end, text: text)
            }
            let lang = raw.language ?? "en"
            let langName = Self.supportedLanguages.first { $0.code == lang }?.name ?? "English"
            return AutoCaptionTrack(language: lang, languageName: langName, segments: segs)
        } catch {
            lastError = error.localizedDescription
            throw error
        }
    }

    // MARK: - Translate captions

    func translate(track: AutoCaptionTrack, to targetLang: String) async throws -> AutoCaptionTrack {
        isTranslating = true
        lastError = nil
        defer { isTranslating = false }

        struct Request: Encodable {
            let task: String
            let source_language: String
            let target_language: String
            let segments: [[String: String]]
        }
        struct RawSeg: Decodable { let text: String? }
        struct Response: Decodable { let translated_segments: [RawSeg]? }

        let segPayload = track.segments.map { ["text": $0.text] }
        let req = Request(
            task: "translate_captions",
            source_language: track.language,
            target_language: targetLang,
            segments: segPayload
        )

        do {
            let raw: Response = try await CloudRunAgentRouter.post(
                .translationAI, path: "/predict", body: req, timeout: 60
            )
            let translated = (raw.translated_segments ?? [])
            let newSegs: [CaptionSegment] = zip(track.segments, translated).map { orig, trans in
                CaptionSegment(start: orig.start, end: orig.end, text: trans.text ?? orig.text)
            }
            let langName = Self.supportedLanguages.first { $0.code == targetLang }?.name ?? targetLang
            return AutoCaptionTrack(language: targetLang, languageName: langName, segments: newSegs)
        } catch {
            lastError = error.localizedDescription
            throw error
        }
    }
}
