//
//  SmartChapterAutoGenService.swift
//  MyChannel
//
//  Auto-generated video chapters: scene detection, topic extraction,
//  chapter title generation, timestamp alignment. Uses `super-ai-team` Cloud Run.
//

import Foundation

struct AutoGeneratedVideoChapter: Codable, Identifiable {
    let id: String
    let videoId: String
    let title: String
    let startSec: Double
    let endSec: Double
    let isAutoGenerated: Bool
}

@MainActor
final class SmartChapterAutoGenService: ObservableObject {
    static let shared = SmartChapterAutoGenService()
    private init() {}
    @Published private(set) var chapters: [AutoGeneratedVideoChapter] = []

    func generateChapters(videoId: String) async throws -> [AutoGeneratedVideoChapter] {
        struct Req: Encodable { let task: String; let videoId: String }
        struct RawC: Decodable { let id: String; let title: String; let start: Double; let end: Double }
        struct Raw: Decodable { let chapters: [RawC]? }
        let r: Raw = try await CloudRunAgentRouter.post(.superAITeam, path: "/predict",
            body: Req(task: "generate_chapters", videoId: videoId), timeout: 45)
        chapters = (r.chapters ?? []).map { AutoGeneratedVideoChapter(id: $0.id, videoId: videoId, title: $0.title, startSec: $0.start, endSec: $0.end, isAutoGenerated: true) }
        return chapters
    }

    func fetchChapters(videoId: String) async throws {
        struct Req: Encodable { let task: String; let videoId: String }
        struct RawC: Decodable { let id: String; let title: String; let start: Double; let end: Double; let auto: Bool }
        struct Raw: Decodable { let chapters: [RawC]? }
        let r: Raw = try await CloudRunAgentRouter.post(.superAITeam, path: "/predict",
            body: Req(task: "fetch_chapters", videoId: videoId))
        chapters = (r.chapters ?? []).map { AutoGeneratedVideoChapter(id: $0.id, videoId: videoId, title: $0.title, startSec: $0.start, endSec: $0.end, isAutoGenerated: $0.auto) }
    }

    func editChapter(chapterId: String, newTitle: String) {
        if let idx = chapters.firstIndex(where: { $0.id == chapterId }) {
            let old = chapters[idx]
            chapters[idx] = AutoGeneratedVideoChapter(id: old.id, videoId: old.videoId, title: newTitle, startSec: old.startSec, endSec: old.endSec, isAutoGenerated: false)
        }
    }
}
