//
//  VideoCaptionsFirestoreService.swift
//  MyChannel
//
//  Firestore-backed captions / subtitles tracks (YouTube Studio "Subtitles"
//  parity). Each video can have multiple caption tracks keyed by language.
//  Tracks are stored at videos/{videoId}/captions/{languageCode} and the raw
//  caption text (SRT/VTT/plain) lives inline for small files.
//

import Foundation
#if canImport(FirebaseFirestore)
import FirebaseFirestore
#endif

// MARK: - Caption Track Model

struct CaptionTrack: Identifiable, Equatable {
    let id: String           // language code, e.g. "en", "es"
    var languageName: String // human-readable, e.g. "English"
    var content: String      // SRT/VTT/plain text body
    var isPublished: Bool
    var isAutoGenerated: Bool
    var updatedAt: Date

    static func == (lhs: CaptionTrack, rhs: CaptionTrack) -> Bool { lhs.id == rhs.id }
}

// MARK: - Common languages for the picker

enum CaptionLanguage: String, CaseIterable, Identifiable {
    case en, es, fr, de, pt, it, ja, ko, zh, hi, ar, ru

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .en: return "English"
        case .es: return "Spanish"
        case .fr: return "French"
        case .de: return "German"
        case .pt: return "Portuguese"
        case .it: return "Italian"
        case .ja: return "Japanese"
        case .ko: return "Korean"
        case .zh: return "Chinese"
        case .hi: return "Hindi"
        case .ar: return "Arabic"
        case .ru: return "Russian"
        }
    }
}

@MainActor
final class VideoCaptionsFirestoreService: ObservableObject {
    static let shared = VideoCaptionsFirestoreService()
    private init() {}

    #if canImport(FirebaseFirestore)
    private var db: Firestore { Firestore.firestore() }
    #endif

    @Published var isLoading = false

    /// All caption tracks for a video.
    func getCaptions(videoId: String) async throws -> [CaptionTrack] {
        #if canImport(FirebaseFirestore)
        guard !videoId.isEmpty else { return [] }
        isLoading = true; defer { isLoading = false }
        let snap = try await db.collection("videos").document(videoId)
            .collection("captions")
            .getDocuments()
        return snap.documents.map { doc in
            let d = doc.data()
            return CaptionTrack(
                id: doc.documentID,
                languageName: d["languageName"] as? String ?? doc.documentID,
                content: d["content"] as? String ?? "",
                isPublished: d["isPublished"] as? Bool ?? false,
                isAutoGenerated: d["isAutoGenerated"] as? Bool ?? false,
                updatedAt: (d["updatedAt"] as? Timestamp)?.dateValue() ?? Date()
            )
        }
        .sorted { $0.languageName < $1.languageName }
        #else
        return []
        #endif
    }

    /// Create or update a caption track. The doc id is the language code.
    func saveCaption(videoId: String, track: CaptionTrack) async throws {
        #if canImport(FirebaseFirestore)
        guard !videoId.isEmpty, !track.id.isEmpty else {
            throw NSError(domain: "Captions", code: 422, userInfo: [NSLocalizedDescriptionKey: "Missing video or language."])
        }
        try await db.collection("videos").document(videoId)
            .collection("captions").document(track.id)
            .setData([
                "languageName": track.languageName,
                "content": track.content,
                "isPublished": track.isPublished,
                "isAutoGenerated": track.isAutoGenerated,
                "updatedAt": FieldValue.serverTimestamp()
            ], merge: true)
        #endif
    }

    func deleteCaption(videoId: String, languageCode: String) async throws {
        #if canImport(FirebaseFirestore)
        guard !videoId.isEmpty, !languageCode.isEmpty else { return }
        try await db.collection("videos").document(videoId)
            .collection("captions").document(languageCode)
            .delete()
        #endif
    }
}
