//
//  VideoCaptionsManagerView.swift
//  MyChannel
//
//  YouTube Studio "Subtitles" parity. Lists caption tracks for a video, lets
//  the creator add a language, paste/edit caption text, publish/unpublish, and
//  delete tracks. Backed by VideoCaptionsFirestoreService.
//

import SwiftUI

struct VideoCaptionsManagerView: View {
    let videoId: String
    let videoTitle: String

    @StateObject private var captionsService = VideoCaptionsFirestoreService.shared
    @State private var tracks: [CaptionTrack] = []
    @State private var isLoading = true
    @State private var editingTrack: CaptionTrack?
    @State private var showingAddLanguage = false

    var body: some View {
        ScrollView {
            LazyVStack(spacing: 20) {
                header

                if isLoading {
                    ProgressView("Loading subtitles…").padding(40)
                } else if tracks.isEmpty {
                    emptyState
                } else {
                    ForEach(tracks) { track in
                        CaptionTrackRow(track: track) {
                            editingTrack = track
                        }
                    }
                }
            }
            .padding(16)
        }
        .navigationTitle("Subtitles")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Button { showingAddLanguage = true } label: {
                    Image(systemName: "plus")
                }
            }
        }
        .task { await loadCaptions() }
        .sheet(isPresented: $showingAddLanguage) {
            CaptionLanguagePicker(existingCodes: Set(tracks.map { $0.id })) { language in
                editingTrack = CaptionTrack(
                    id: language.rawValue,
                    languageName: language.displayName,
                    content: "",
                    isPublished: false,
                    isAutoGenerated: false,
                    updatedAt: Date()
                )
            }
        }
        .sheet(item: $editingTrack) { track in
            CaptionEditorSheet(videoId: videoId, track: track) {
                Task { await loadCaptions() }
            }
        }
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(videoTitle)
                .font(.system(size: 16, weight: .semibold))
                .lineLimit(2)
            Text("Add subtitles in multiple languages so more viewers can watch. Published tracks appear in the player's CC menu.")
                .font(.system(size: 13))
                .foregroundColor(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(14)
        .background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 12))
    }

    private var emptyState: some View {
        VStack(spacing: 12) {
            Image(systemName: "captions.bubble")
                .font(.system(size: 50))
                .foregroundColor(.secondary)
            Text("No subtitles yet")
                .font(.system(size: 18, weight: .semibold))
            Text("Tap + to add your first language.")
                .font(.system(size: 14))
                .foregroundColor(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(40)
    }

    private func loadCaptions() async {
        let loaded = (try? await captionsService.getCaptions(videoId: videoId)) ?? []
        await MainActor.run {
            tracks = loaded
            isLoading = false
        }
    }
}

// MARK: - Track Row

struct CaptionTrackRow: View {
    let track: CaptionTrack
    let onTap: () -> Void

    var body: some View {
        Button(action: onTap) {
            HStack(spacing: 12) {
                Image(systemName: "captions.bubble.fill")
                    .font(.system(size: 22))
                    .foregroundColor(AppTheme.Colors.primary)
                    .frame(width: 44, height: 44)
                    .background(AppTheme.Colors.primary.opacity(0.15), in: Circle())

                VStack(alignment: .leading, spacing: 4) {
                    Text(track.languageName)
                        .font(.system(size: 15, weight: .semibold))
                    HStack(spacing: 8) {
                        Text(track.isPublished ? "Published" : "Draft")
                            .font(.system(size: 11, weight: .semibold))
                            .foregroundColor(track.isPublished ? .green : .orange)
                        if track.isAutoGenerated {
                            Text("Auto")
                                .font(.system(size: 11, weight: .semibold))
                                .foregroundColor(.secondary)
                        }
                    }
                }

                Spacer()

                Image(systemName: "chevron.right")
                    .foregroundColor(.secondary)
            }
            .padding(12)
            .background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 12))
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Language Picker

struct CaptionLanguagePicker: View {
    @Environment(\.dismiss) private var dismiss
    let existingCodes: Set<String>
    let onPick: (CaptionLanguage) -> Void

    var body: some View {
        NavigationStack {
            List(CaptionLanguage.allCases) { language in
                Button {
                    onPick(language)
                    dismiss()
                } label: {
                    HStack {
                        Text(language.displayName)
                        Spacer()
                        if existingCodes.contains(language.rawValue) {
                            Text("Added")
                                .font(.system(size: 12))
                                .foregroundColor(.secondary)
                        }
                    }
                }
                .disabled(existingCodes.contains(language.rawValue))
            }
            .navigationTitle("Add Language")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Cancel") { dismiss() }
                }
            }
        }
    }
}

// MARK: - Editor

struct CaptionEditorSheet: View {
    @Environment(\.dismiss) private var dismiss
    let videoId: String
    let track: CaptionTrack
    var onSaved: () -> Void = {}

    @StateObject private var captionsService = VideoCaptionsFirestoreService.shared
    @State private var content: String
    @State private var isPublished: Bool
    @State private var isSaving = false
    @State private var showingDeleteConfirm = false
    @State private var errorMessage: String?

    init(videoId: String, track: CaptionTrack, onSaved: @escaping () -> Void = {}) {
        self.videoId = videoId
        self.track = track
        self.onSaved = onSaved
        _content = State(initialValue: track.content)
        _isPublished = State(initialValue: track.isPublished)
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Subtitle text") {
                    TextEditor(text: $content)
                        .frame(minHeight: 220)
                        .font(.system(.body, design: .monospaced))
                    Text("Paste SRT/VTT or plain text. Timecodes are kept as-is.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Section {
                    Toggle("Published", isOn: $isPublished)
                    Text(isPublished
                         ? "Visible to viewers in the player's CC menu."
                         : "Saved as a draft — not shown to viewers yet.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                if let errorMessage {
                    Section {
                        Text(errorMessage).font(.system(size: 13)).foregroundColor(.red)
                    }
                }

                Section {
                    Button {
                        Task { await save() }
                    } label: {
                        HStack {
                            if isSaving { ProgressView().padding(.trailing, 4) }
                            Text(isSaving ? "Saving…" : "Save")
                        }
                    }
                    .disabled(content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || isSaving)

                    Button("Delete Track", role: .destructive) {
                        showingDeleteConfirm = true
                    }
                }
            }
            .navigationTitle(track.languageName)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Cancel") { dismiss() }
                }
            }
            .alert("Delete Subtitles?", isPresented: $showingDeleteConfirm) {
                Button("Cancel", role: .cancel) {}
                Button("Delete", role: .destructive) {
                    Task { await deleteTrack() }
                }
            } message: {
                Text("This removes the \(track.languageName) subtitle track from this video.")
            }
        }
    }

    private func save() async {
        isSaving = true
        errorMessage = nil
        var updated = track
        updated.content = content
        updated.isPublished = isPublished
        do {
            try await captionsService.saveCaption(videoId: videoId, track: updated)
            HapticManager.shared.notification(type: .success)
            onSaved()
            dismiss()
        } catch {
            isSaving = false
            errorMessage = error.localizedDescription
        }
    }

    private func deleteTrack() async {
        isSaving = true
        errorMessage = nil
        do {
            try await captionsService.deleteCaption(videoId: videoId, languageCode: track.id)
            HapticManager.shared.notification(type: .success)
            onSaved()
            dismiss()
        } catch {
            isSaving = false
            errorMessage = error.localizedDescription
        }
    }
}
